/**
 * @typedef {'is'|'color'|'sound'|'texture'|'shape'|'evokes'|'rhymes'|'collides'|'transforms'|'consumes'|'produces'} Relation
 * @typedef {[string, Relation, string]} Triple
 * @typedef {{ concept: string, relation: Relation, direction: 'fwd'|'rev' }} Edge
 * @typedef {Map<string, Edge[]>} ConceptGraph
 */

/** @type {Relation[]} */
export const RELATION_TYPES = [
  'is', 'color', 'sound', 'texture', 'shape',
  'evokes', 'rhymes', 'collides', 'transforms', 'consumes', 'produces',
]

// ── Narrative edges — carry story weight, weighted higher in walks ──
export const NARRATIVE_RELATIONS = new Set([
  'transforms', 'consumes', 'produces', 'collides', 'evokes',
])

/**
 * The concept graph — flat array of triples [subject, relation, object].
 * Grouped by domain for readability. The graph is the vocabulary; the
 * walker and myth assembler provide the grammar.
 *
 * `is` categories: element, celestial, material, body, force, place, flora, fauna, item
 * @type {Triple[]}
 */
export const TRIPLES = [

  // ── Fire ──
  ['fire', 'is', 'element'],
  ['fire', 'color', 'gold'],
  ['fire', 'color', 'red'],
  ['fire', 'sound', 'roar'],
  ['fire', 'texture', 'rough'],
  ['fire', 'evokes', 'hunger'],
  ['fire', 'evokes', 'rage'],
  ['fire', 'collides', 'water'],
  ['fire', 'collides', 'silence'],
  ['fire', 'transforms', 'ash'],
  ['fire', 'consumes', 'flesh'],
  ['fire', 'produces', 'smoke'],
  ['fire', 'produces', 'light'],
  ['fire', 'rhymes', 'sun'],

  // ── Water ──
  ['water', 'is', 'element'],
  ['water', 'color', 'blue'],
  ['water', 'sound', 'whisper'],
  ['water', 'texture', 'smooth'],
  ['water', 'evokes', 'memory'],
  ['water', 'evokes', 'grief'],
  ['water', 'collides', 'stone'],
  ['water', 'transforms', 'ice'],
  ['water', 'transforms', 'rust'],
  ['water', 'consumes', 'salt'],
  ['water', 'produces', 'mist'],
  ['water', 'rhymes', 'blood'],
  ['water', 'rhymes', 'time'],

  // ── Stone / Earth ──
  ['stone', 'is', 'element'],
  ['stone', 'color', 'grey'],
  ['stone', 'texture', 'rough'],
  ['stone', 'shape', 'slab'],
  ['stone', 'evokes', 'endurance'],
  ['stone', 'evokes', 'silence'],
  ['stone', 'collides', 'time'],
  ['stone', 'transforms', 'dust'],
  ['stone', 'produces', 'echo'],
  ['stone', 'consumes', 'bone'],
  ['stone', 'rhymes', 'bone'],
  ['stone', 'rhymes', 'silence'],

  // ── Void / Darkness ──
  ['void', 'is', 'element'],
  ['void', 'color', 'black'],
  ['void', 'sound', 'silence'],
  ['void', 'evokes', 'hunger'],
  ['void', 'evokes', 'longing'],
  ['void', 'collides', 'light'],
  ['void', 'collides', 'fullness'],
  ['void', 'transforms', 'silence'],
  ['void', 'consumes', 'memory'],
  ['void', 'consumes', 'name'],
  ['void', 'produces', 'echo'],
  ['void', 'rhymes', 'sleep'],
  ['void', 'rhymes', 'death'],

  // ── Light ──
  ['light', 'is', 'element'],
  ['light', 'color', 'white'],
  ['light', 'sound', 'ring'],
  ['light', 'evokes', 'truth'],
  ['light', 'evokes', 'wound'],
  ['light', 'collides', 'shadow'],
  ['light', 'transforms', 'shadow'],
  ['light', 'consumes', 'shadow'],
  ['light', 'produces', 'warmth'],
  ['light', 'rhymes', 'hope'],
  ['light', 'rhymes', 'eye'],

  // ── Shadow ──
  ['shadow', 'is', 'element'],
  ['shadow', 'color', 'grey'],
  ['shadow', 'evokes', 'fear'],
  ['shadow', 'evokes', 'memory'],
  ['shadow', 'collides', 'light'],
  ['shadow', 'transforms', 'night'],
  ['shadow', 'produces', 'fear'],
  ['shadow', 'consumes', 'warmth'],
  ['shadow', 'rhymes', 'lie'],
  ['shadow', 'rhymes', 'silence'],
  ['shadow', 'sound', 'hush'],

  // ── Wind / Storm ──
  ['wind', 'is', 'element'],
  ['wind', 'sound', 'roar'],
  ['wind', 'sound', 'whisper'],
  ['wind', 'evokes', 'longing'],
  ['wind', 'evokes', 'grief'],
  ['wind', 'collides', 'stone'],
  ['wind', 'transforms', 'dust'],
  ['wind', 'produces', 'sound'],
  ['wind', 'consumes', 'smoke'],
  ['wind', 'rhymes', 'breath'],
  ['wind', 'rhymes', 'time'],

  // ── Celestial ──
  ['sun', 'is', 'celestial'],
  ['sun', 'color', 'gold'],
  ['sun', 'shape', 'circle'],
  ['sun', 'evokes', 'pride'],
  ['sun', 'evokes', 'wrath'],
  ['sun', 'collides', 'moon'],
  ['sun', 'transforms', 'shadow'],
  ['sun', 'consumes', 'night'],
  ['sun', 'produces', 'shadow'],
  ['sun', 'produces', 'warmth'],
  ['sun', 'rhymes', 'eye'],
  ['sun', 'rhymes', 'fire'],
  ['sun', 'sound', 'roar'],

  ['moon', 'is', 'celestial'],
  ['moon', 'color', 'silver'],
  ['moon', 'shape', 'crescent'],
  ['moon', 'evokes', 'grief'],
  ['moon', 'evokes', 'longing'],
  ['moon', 'collides', 'sun'],
  ['moon', 'transforms', 'tide'],
  ['moon', 'consumes', 'night'],
  ['moon', 'produces', 'tide'],
  ['moon', 'rhymes', 'bone'],
  ['moon', 'rhymes', 'wound'],
  ['moon', 'sound', 'hush'],

  ['star', 'is', 'celestial'],
  ['star', 'color', 'silver'],
  ['star', 'shape', 'point'],
  ['star', 'evokes', 'hope'],
  ['star', 'evokes', 'longing'],
  ['star', 'collides', 'void'],
  ['star', 'transforms', 'ash'],
  ['star', 'produces', 'light'],
  ['star', 'rhymes', 'eye'],
  ['star', 'rhymes', 'wound'],
  ['star', 'sound', 'ring'],

  ['dawn', 'is', 'celestial'],
  ['dawn', 'color', 'gold'],
  ['dawn', 'color', 'red'],
  ['dawn', 'evokes', 'hope'],
  ['dawn', 'evokes', 'grief'],
  ['dawn', 'collides', 'night'],
  ['dawn', 'transforms', 'shadow'],
  ['dawn', 'produces', 'light'],
  ['dawn', 'rhymes', 'bone'],
  ['dawn', 'rhymes', 'wound'],

  ['dusk', 'is', 'celestial'],
  ['dusk', 'color', 'gold'],
  ['dusk', 'color', 'red'],
  ['dusk', 'evokes', 'grief'],
  ['dusk', 'evokes', 'longing'],
  ['dusk', 'collides', 'dawn'],
  ['dusk', 'transforms', 'night'],
  ['dusk', 'produces', 'shadow'],
  ['dusk', 'rhymes', 'dust'],
  ['dusk', 'rhymes', 'ash'],

  // ── Materials / Substances ──
  ['bone', 'is', 'material'],
  ['bone', 'color', 'white'],
  ['bone', 'texture', 'smooth'],
  ['bone', 'shape', 'shard'],
  ['bone', 'evokes', 'death'],
  ['bone', 'evokes', 'endurance'],
  ['bone', 'collides', 'flesh'],
  ['bone', 'transforms', 'dust'],
  ['bone', 'transforms', 'knife'],
  ['bone', 'produces', 'echo'],
  ['bone', 'rhymes', 'stone'],
  ['bone', 'rhymes', 'moon'],
  ['bone', 'sound', 'crack'],

  ['blood', 'is', 'material'],
  ['blood', 'color', 'red'],
  ['blood', 'texture', 'wet'],
  ['blood', 'evokes', 'life'],
  ['blood', 'evokes', 'sacrifice'],
  ['blood', 'collides', 'dust'],
  ['blood', 'transforms', 'river'],
  ['blood', 'transforms', 'rust'],
  ['blood', 'produces', 'soil'],
  ['blood', 'rhymes', 'water'],
  ['blood', 'rhymes', 'truth'],
  ['blood', 'sound', 'drum'],

  ['ash', 'is', 'material'],
  ['ash', 'color', 'grey'],
  ['ash', 'texture', 'rough'],
  ['ash', 'evokes', 'grief'],
  ['ash', 'evokes', 'memory'],
  ['ash', 'collides', 'wind'],
  ['ash', 'transforms', 'soil'],
  ['ash', 'produces', 'soil'],
  ['ash', 'rhymes', 'dust'],
  ['ash', 'rhymes', 'snow'],
  ['ash', 'rhymes', 'bone'],
  ['ash', 'sound', 'hush'],

  ['dust', 'is', 'material'],
  ['dust', 'color', 'grey'],
  ['dust', 'texture', 'rough'],
  ['dust', 'evokes', 'neglect'],
  ['dust', 'evokes', 'death'],
  ['dust', 'collides', 'wind'],
  ['dust', 'collides', 'water'],
  ['dust', 'transforms', 'soil'],
  ['dust', 'produces', 'silence'],
  ['dust', 'rhymes', 'ash'],
  ['dust', 'rhymes', 'silence'],
  ['dust', 'sound', 'hush'],

  ['salt', 'is', 'material'],
  ['salt', 'color', 'white'],
  ['salt', 'texture', 'rough'],
  ['salt', 'evokes', 'grief'],
  ['salt', 'evokes', 'preservation'],
  ['salt', 'collides', 'wound'],
  ['salt', 'transforms', 'stone'],
  ['salt', 'produces', 'grief'],
  ['salt', 'consumes', 'flesh'],
  ['salt', 'rhymes', 'bone'],
  ['salt', 'rhymes', 'tear'],
  ['salt', 'sound', 'crack'],

  ['gold', 'is', 'material'],
  ['gold', 'color', 'gold'],
  ['gold', 'texture', 'smooth'],
  ['gold', 'evokes', 'pride'],
  ['gold', 'evokes', 'corruption'],
  ['gold', 'collides', 'iron'],
  ['gold', 'collides', 'rust'],
  ['gold', 'transforms', 'ash'],
  ['gold', 'transforms', 'mask'],
  ['gold', 'produces', 'longing'],
  ['gold', 'rhymes', 'sun'],
  ['gold', 'rhymes', 'light'],
  ['gold', 'sound', 'ring'],

  ['iron', 'is', 'material'],
  ['iron', 'color', 'grey'],
  ['iron', 'texture', 'rough'],
  ['iron', 'evokes', 'endurance'],
  ['iron', 'evokes', 'will'],
  ['iron', 'collides', 'flesh'],
  ['iron', 'transforms', 'rust'],
  ['iron', 'transforms', 'sword'],
  ['iron', 'transforms', 'knife'],
  ['iron', 'transforms', 'plow'],
  ['iron', 'produces', 'wound'],
  ['iron', 'consumes', 'bone'],
  ['iron', 'rhymes', 'stone'],
  ['iron', 'sound', 'crack'],

  ['glass', 'is', 'material'],
  ['glass', 'color', 'clear'],
  ['glass', 'texture', 'smooth'],
  ['glass', 'shape', 'shard'],
  ['glass', 'evokes', 'truth'],
  ['glass', 'evokes', 'fragility'],
  ['glass', 'collides', 'stone'],
  ['glass', 'produces', 'light'],
  ['glass', 'consumes', 'light'],
  ['glass', 'transforms', 'dust'],
  ['glass', 'rhymes', 'eye'],
  ['glass', 'rhymes', 'mirror'],
  ['glass', 'sound', 'ring'],

  ['ice', 'is', 'material'],
  ['ice', 'color', 'blue'],
  ['ice', 'texture', 'smooth'],
  ['ice', 'evokes', 'silence'],
  ['ice', 'evokes', 'endurance'],
  ['ice', 'collides', 'fire'],
  ['ice', 'transforms', 'water'],
  ['ice', 'consumes', 'warmth'],
  ['ice', 'produces', 'silence'],
  ['ice', 'rhymes', 'death'],
  ['ice', 'rhymes', 'stone'],
  ['ice', 'sound', 'crack'],

  ['rust', 'is', 'material'],
  ['rust', 'color', 'red'],
  ['rust', 'evokes', 'time'],
  ['rust', 'evokes', 'decay'],
  ['rust', 'collides', 'gold'],
  ['rust', 'transforms', 'dust'],
  ['rust', 'consumes', 'iron'],
  ['rust', 'produces', 'dust'],
  ['rust', 'rhymes', 'blood'],
  ['rust', 'rhymes', 'ash'],

  ['smoke', 'is', 'material'],
  ['smoke', 'color', 'grey'],
  ['smoke', 'evokes', 'memory'],
  ['smoke', 'evokes', 'grief'],
  ['smoke', 'collides', 'wind'],
  ['smoke', 'transforms', 'mist'],
  ['smoke', 'produces', 'shadow'],
  ['smoke', 'rhymes', 'ghost'],
  ['smoke', 'rhymes', 'ash'],
  ['smoke', 'sound', 'hush'],

  ['soil', 'is', 'material'],
  ['soil', 'evokes', 'life'],
  ['soil', 'evokes', 'death'],
  ['soil', 'produces', 'root'],
  ['soil', 'produces', 'seed'],
  ['soil', 'consumes', 'bone'],
  ['soil', 'consumes', 'blood'],
  ['soil', 'color', 'brown'],
  ['soil', 'transforms', 'clay'],
  ['soil', 'rhymes', 'ash'],
  ['soil', 'rhymes', 'dust'],

  ['tear', 'is', 'material'],
  ['tear', 'evokes', 'grief'],
  ['tear', 'evokes', 'memory'],
  ['tear', 'collides', 'fire'],
  ['tear', 'transforms', 'salt'],
  ['tear', 'color', 'clear'],
  ['tear', 'produces', 'salt'],
  ['tear', 'rhymes', 'blood'],
  ['tear', 'rhymes', 'water'],

  ['mist', 'is', 'material'],
  ['mist', 'evokes', 'forgetting'],
  ['mist', 'evokes', 'memory'],
  ['mist', 'collides', 'fire'],
  ['mist', 'collides', 'light'],
  ['mist', 'transforms', 'water'],
  ['mist', 'color', 'white'],
  ['mist', 'produces', 'silence'],
  ['mist', 'rhymes', 'ghost'],
  ['mist', 'rhymes', 'breath'],

  ['snow', 'is', 'material'],
  ['snow', 'color', 'white'],
  ['snow', 'texture', 'smooth'],
  ['snow', 'evokes', 'silence'],
  ['snow', 'evokes', 'death'],
  ['snow', 'collides', 'fire'],
  ['snow', 'transforms', 'water'],
  ['snow', 'produces', 'silence'],
  ['snow', 'rhymes', 'ash'],
  ['snow', 'rhymes', 'bone'],

  ['thread', 'is', 'material'],
  ['thread', 'evokes', 'fate'],
  ['thread', 'evokes', 'patience'],
  ['thread', 'collides', 'wind'],
  ['thread', 'produces', 'web'],
  ['thread', 'color', 'white'],
  ['thread', 'transforms', 'net'],
  ['thread', 'rhymes', 'river'],
  ['thread', 'rhymes', 'vein'],

  ['seed', 'is', 'material'],
  ['seed', 'evokes', 'hope'],
  ['seed', 'evokes', 'patience'],
  ['seed', 'collides', 'stone'],
  ['seed', 'collides', 'fire'],
  ['seed', 'transforms', 'tree'],
  ['seed', 'produces', 'root'],
  ['seed', 'produces', 'flower'],
  ['seed', 'color', 'brown'],
  ['seed', 'rhymes', 'blood'],
  ['seed', 'rhymes', 'dream'],

  ['wax', 'is', 'material'],
  ['wax', 'color', 'gold'],
  ['wax', 'texture', 'smooth'],
  ['wax', 'evokes', 'time'],
  ['wax', 'evokes', 'fragility'],
  ['wax', 'collides', 'fire'],
  ['wax', 'transforms', 'smoke'],
  ['wax', 'transforms', 'mask'],
  ['wax', 'produces', 'light'],
  ['wax', 'rhymes', 'bone'],
  ['wax', 'rhymes', 'moon'],
  ['wax', 'sound', 'hush'],

  // ── Body / Physical ──
  ['eye', 'is', 'body'],
  ['eye', 'color', 'varied'],
  ['eye', 'shape', 'circle'],
  ['eye', 'evokes', 'truth'],
  ['eye', 'evokes', 'wound'],
  ['eye', 'collides', 'shadow'],
  ['eye', 'transforms', 'tear'],
  ['eye', 'produces', 'tear'],
  ['eye', 'consumes', 'light'],
  ['eye', 'rhymes', 'sun'],
  ['eye', 'rhymes', 'star'],

  ['mouth', 'is', 'body'],
  ['mouth', 'shape', 'hollow'],
  ['mouth', 'evokes', 'hunger'],
  ['mouth', 'evokes', 'lie'],
  ['mouth', 'color', 'red'],
  ['mouth', 'produces', 'sound'],
  ['mouth', 'produces', 'breath'],
  ['mouth', 'consumes', 'silence'],
  ['mouth', 'transforms', 'wound'],
  ['mouth', 'rhymes', 'wound'],
  ['mouth', 'rhymes', 'cave'],

  ['hand', 'is', 'body'],
  ['hand', 'shape', 'branch'],
  ['hand', 'evokes', 'will'],
  ['hand', 'evokes', 'creation'],
  ['hand', 'color', 'varied'],
  ['hand', 'collides', 'wound'],
  ['hand', 'transforms', 'stone'],
  ['hand', 'produces', 'wound'],
  ['hand', 'consumes', 'time'],
  ['hand', 'rhymes', 'wound'],

  ['breath', 'is', 'body'],
  ['breath', 'evokes', 'life'],
  ['breath', 'evokes', 'time'],
  ['breath', 'collides', 'stone'],
  ['breath', 'transforms', 'wind'],
  ['breath', 'produces', 'mist'],
  ['breath', 'consumes', 'silence'],
  ['breath', 'rhymes', 'wind'],
  ['breath', 'rhymes', 'ghost'],

  ['wound', 'is', 'body'],
  ['wound', 'color', 'red'],
  ['wound', 'evokes', 'grief'],
  ['wound', 'evokes', 'memory'],
  ['wound', 'collides', 'time'],
  ['wound', 'transforms', 'scar'],
  ['wound', 'produces', 'blood'],
  ['wound', 'consumes', 'silence'],
  ['wound', 'rhymes', 'star'],
  ['wound', 'rhymes', 'moon'],

  ['flesh', 'is', 'body'],
  ['flesh', 'color', 'red'],
  ['flesh', 'texture', 'wet'],
  ['flesh', 'evokes', 'hunger'],
  ['flesh', 'evokes', 'wound'],
  ['flesh', 'collides', 'iron'],
  ['flesh', 'transforms', 'ash'],
  ['flesh', 'transforms', 'soil'],
  ['flesh', 'produces', 'blood'],
  ['flesh', 'rhymes', 'breath'],
  ['flesh', 'rhymes', 'wound'],
  ['flesh', 'sound', 'drum'],

  ['skull', 'is', 'body'],
  ['skull', 'color', 'white'],
  ['skull', 'shape', 'hollow'],
  ['skull', 'evokes', 'death'],
  ['skull', 'evokes', 'memory'],
  ['skull', 'collides', 'stone'],
  ['skull', 'produces', 'echo'],
  ['skull', 'transforms', 'dust'],
  ['skull', 'rhymes', 'moon'],
  ['skull', 'rhymes', 'bone'],
  ['skull', 'sound', 'crack'],

  // ── Abstract / Forces ──
  ['silence', 'is', 'force'],
  ['silence', 'evokes', 'death'],
  ['silence', 'evokes', 'endurance'],
  ['silence', 'collides', 'sound'],
  ['silence', 'collides', 'fire'],
  ['silence', 'transforms', 'stone'],
  ['silence', 'produces', 'echo'],
  ['silence', 'consumes', 'song'],
  ['silence', 'rhymes', 'void'],
  ['silence', 'rhymes', 'stone'],
  ['silence', 'color', 'white'],
  ['silence', 'texture', 'smooth'],

  ['dream', 'is', 'force'],
  ['dream', 'evokes', 'truth'],
  ['dream', 'evokes', 'lie'],
  ['dream', 'collides', 'waking'],
  ['dream', 'transforms', 'memory'],
  ['dream', 'produces', 'shadow'],
  ['dream', 'consumes', 'fear'],
  ['dream', 'rhymes', 'sleep'],
  ['dream', 'rhymes', 'echo'],
  ['dream', 'sound', 'whisper'],
  ['dream', 'color', 'silver'],
  ['dream', 'texture', 'soft'],

  ['memory', 'is', 'force'],
  ['memory', 'evokes', 'grief'],
  ['memory', 'evokes', 'wound'],
  ['memory', 'collides', 'forgetting'],
  ['memory', 'transforms', 'ghost'],
  ['memory', 'produces', 'wound'],
  ['memory', 'consumes', 'sleep'],
  ['memory', 'rhymes', 'water'],
  ['memory', 'rhymes', 'ash'],
  ['memory', 'color', 'grey'],
  ['memory', 'sound', 'whisper'],

  ['time', 'is', 'force'],
  ['time', 'evokes', 'grief'],
  ['time', 'evokes', 'endurance'],
  ['time', 'collides', 'stone'],
  ['time', 'transforms', 'dust'],
  ['time', 'produces', 'rust'],
  ['time', 'consumes', 'memory'],
  ['time', 'rhymes', 'water'],
  ['time', 'rhymes', 'wind'],
  ['time', 'color', 'grey'],
  ['time', 'texture', 'smooth'],

  ['truth', 'is', 'force'],
  ['truth', 'evokes', 'wound'],
  ['truth', 'evokes', 'light'],
  ['truth', 'collides', 'lie'],
  ['truth', 'transforms', 'wound'],
  ['truth', 'produces', 'grief'],
  ['truth', 'consumes', 'lie'],
  ['truth', 'rhymes', 'glass'],
  ['truth', 'rhymes', 'blood'],
  ['truth', 'color', 'white'],
  ['truth', 'texture', 'sharp'],

  ['lie', 'is', 'force'],
  ['lie', 'evokes', 'shadow'],
  ['lie', 'evokes', 'hunger'],
  ['lie', 'collides', 'truth'],
  ['lie', 'transforms', 'fear'],
  ['lie', 'produces', 'silence'],
  ['lie', 'consumes', 'name'],
  ['lie', 'rhymes', 'mouth'],
  ['lie', 'rhymes', 'shadow'],
  ['lie', 'color', 'black'],
  ['lie', 'texture', 'smooth'],

  ['hunger', 'is', 'force'],
  ['hunger', 'evokes', 'void'],
  ['hunger', 'evokes', 'rage'],
  ['hunger', 'collides', 'fullness'],
  ['hunger', 'transforms', 'rage'],
  ['hunger', 'produces', 'wound'],
  ['hunger', 'consumes', 'silence'],
  ['hunger', 'rhymes', 'longing'],
  ['hunger', 'shape', 'hollow'],
  ['hunger', 'texture', 'rough'],
  ['hunger', 'sound', 'moan'],

  ['grief', 'is', 'force'],
  ['grief', 'evokes', 'silence'],
  ['grief', 'evokes', 'memory'],
  ['grief', 'collides', 'joy'],
  ['grief', 'transforms', 'silence'],
  ['grief', 'produces', 'tear'],
  ['grief', 'consumes', 'memory'],
  ['grief', 'rhymes', 'water'],
  ['grief', 'rhymes', 'ash'],
  ['grief', 'color', 'grey'],
  ['grief', 'sound', 'moan'],

  ['longing', 'is', 'force'],
  ['longing', 'evokes', 'wound'],
  ['longing', 'evokes', 'moon'],
  ['longing', 'collides', 'presence'],
  ['longing', 'transforms', 'grief'],
  ['longing', 'produces', 'song'],
  ['longing', 'consumes', 'sleep'],
  ['longing', 'rhymes', 'hunger'],
  ['longing', 'rhymes', 'echo'],
  ['longing', 'sound', 'whisper'],
  ['longing', 'texture', 'smooth'],

  ['echo', 'is', 'force'],
  ['echo', 'evokes', 'memory'],
  ['echo', 'evokes', 'grief'],
  ['echo', 'collides', 'silence'],
  ['echo', 'transforms', 'silence'],
  ['echo', 'produces', 'silence'],
  ['echo', 'consumes', 'sound'],
  ['echo', 'rhymes', 'dream'],
  ['echo', 'rhymes', 'shadow'],
  ['echo', 'color', 'silver'],
  ['echo', 'sound', 'whisper'],

  ['death', 'is', 'force'],
  ['death', 'evokes', 'silence'],
  ['death', 'evokes', 'bone'],
  ['death', 'collides', 'life'],
  ['death', 'transforms', 'memory'],
  ['death', 'produces', 'soil'],
  ['death', 'consumes', 'name'],
  ['death', 'rhymes', 'sleep'],
  ['death', 'rhymes', 'void'],
  ['death', 'color', 'black'],
  ['death', 'sound', 'hush'],

  ['sleep', 'is', 'force'],
  ['sleep', 'evokes', 'silence'],
  ['sleep', 'evokes', 'dream'],
  ['sleep', 'collides', 'waking'],
  ['sleep', 'transforms', 'dream'],
  ['sleep', 'produces', 'shadow'],
  ['sleep', 'consumes', 'grief'],
  ['sleep', 'rhymes', 'death'],
  ['sleep', 'rhymes', 'void'],
  ['sleep', 'color', 'black'],
  ['sleep', 'texture', 'soft'],
  ['sleep', 'sound', 'hush'],

  ['night', 'is', 'force'],
  ['night', 'color', 'black'],
  ['night', 'evokes', 'fear'],
  ['night', 'evokes', 'dream'],
  ['night', 'collides', 'dawn'],
  ['night', 'transforms', 'shadow'],
  ['night', 'produces', 'dream'],
  ['night', 'consumes', 'light'],
  ['night', 'rhymes', 'death'],
  ['night', 'rhymes', 'void'],
  ['night', 'sound', 'hush'],

  ['name', 'is', 'force'],
  ['name', 'evokes', 'truth'],
  ['name', 'evokes', 'power'],
  ['name', 'collides', 'silence'],
  ['name', 'transforms', 'memory'],
  ['name', 'produces', 'echo'],
  ['name', 'consumes', 'silence'],
  ['name', 'rhymes', 'echo'],
  ['name', 'rhymes', 'breath'],
  ['name', 'color', 'gold'],
  ['name', 'sound', 'whisper'],

  ['fear', 'is', 'force'],
  ['fear', 'evokes', 'void'],
  ['fear', 'evokes', 'silence'],
  ['fear', 'collides', 'truth'],
  ['fear', 'collides', 'light'],
  ['fear', 'transforms', 'rage'],
  ['fear', 'produces', 'silence'],
  ['fear', 'rhymes', 'shadow'],
  ['fear', 'rhymes', 'night'],
  ['fear', 'color', 'black'],
  ['fear', 'texture', 'cold'],
  ['fear', 'sound', 'hush'],

  ['rage', 'is', 'force'],
  ['rage', 'evokes', 'fire'],
  ['rage', 'evokes', 'wound'],
  ['rage', 'collides', 'stone'],
  ['rage', 'transforms', 'grief'],
  ['rage', 'produces', 'wound'],
  ['rage', 'consumes', 'silence'],
  ['rage', 'rhymes', 'hunger'],
  ['rage', 'rhymes', 'fire'],
  ['rage', 'color', 'red'],
  ['rage', 'sound', 'roar'],

  ['life', 'is', 'force'],
  ['life', 'evokes', 'breath'],
  ['life', 'evokes', 'hunger'],
  ['life', 'collides', 'death'],
  ['life', 'transforms', 'memory'],
  ['life', 'produces', 'blood'],
  ['life', 'produces', 'wound'],
  ['life', 'rhymes', 'light'],
  ['life', 'rhymes', 'river'],
  ['life', 'color', 'green'],
  ['life', 'sound', 'hum'],

  ['wisdom', 'is', 'force'],
  ['wisdom', 'evokes', 'silence'],
  ['wisdom', 'evokes', 'time'],
  ['wisdom', 'collides', 'lie'],
  ['wisdom', 'transforms', 'truth'],
  ['wisdom', 'produces', 'grief'],
  ['wisdom', 'consumes', 'lie'],
  ['wisdom', 'rhymes', 'time'],
  ['wisdom', 'rhymes', 'bone'],
  ['wisdom', 'color', 'gold'],
  ['wisdom', 'texture', 'smooth'],
  ['wisdom', 'sound', 'hum'],

  ['song', 'is', 'force'],
  ['song', 'evokes', 'memory'],
  ['song', 'evokes', 'longing'],
  ['song', 'collides', 'silence'],
  ['song', 'transforms', 'grief'],
  ['song', 'produces', 'tear'],
  ['song', 'consumes', 'silence'],
  ['song', 'rhymes', 'wind'],
  ['song', 'rhymes', 'bone'],
  ['song', 'sound', 'hum'],
  ['song', 'texture', 'smooth'],

  ['fate', 'is', 'force'],
  ['fate', 'evokes', 'silence'],
  ['fate', 'evokes', 'fear'],
  ['fate', 'collides', 'will'],
  ['fate', 'collides', 'name'],
  ['fate', 'transforms', 'dream'],
  ['fate', 'produces', 'grief'],
  ['fate', 'consumes', 'life'],
  ['fate', 'rhymes', 'death'],
  ['fate', 'rhymes', 'stone'],
  ['fate', 'color', 'grey'],
  ['fate', 'shape', 'spiral'],

  ['wrath', 'is', 'force'],
  ['wrath', 'evokes', 'fire'],
  ['wrath', 'evokes', 'wound'],
  ['wrath', 'collides', 'silence'],
  ['wrath', 'collides', 'stone'],
  ['wrath', 'transforms', 'grief'],
  ['wrath', 'produces', 'ash'],
  ['wrath', 'produces', 'wound'],
  ['wrath', 'consumes', 'reason'],
  ['wrath', 'rhymes', 'fire'],
  ['wrath', 'rhymes', 'blood'],
  ['wrath', 'color', 'red'],
  ['wrath', 'sound', 'roar'],

  // ── Weather ──
  ['cloud', 'is', 'element'],
  ['cloud', 'color', 'grey'],
  ['cloud', 'color', 'white'],
  ['cloud', 'shape', 'hollow'],
  ['cloud', 'evokes', 'grief'],
  ['cloud', 'evokes', 'forgetting'],
  ['cloud', 'collides', 'sun'],
  ['cloud', 'collides', 'mountain'],
  ['cloud', 'transforms', 'rain'],
  ['cloud', 'produces', 'shadow'],
  ['cloud', 'produces', 'rain'],
  ['cloud', 'consumes', 'light'],
  ['cloud', 'rhymes', 'mist'],
  ['cloud', 'rhymes', 'ghost'],

  ['rain', 'is', 'element'],
  ['rain', 'color', 'grey'],
  ['rain', 'sound', 'whisper'],
  ['rain', 'texture', 'wet'],
  ['rain', 'evokes', 'grief'],
  ['rain', 'evokes', 'memory'],
  ['rain', 'collides', 'fire'],
  ['rain', 'collides', 'dust'],
  ['rain', 'transforms', 'dust'],
  ['rain', 'transforms', 'river'],
  ['rain', 'produces', 'river'],
  ['rain', 'produces', 'soil'],
  ['rain', 'consumes', 'fire'],
  ['rain', 'rhymes', 'tear'],
  ['rain', 'rhymes', 'blood'],

  ['fog', 'is', 'element'],
  ['fog', 'color', 'grey'],
  ['fog', 'evokes', 'forgetting'],
  ['fog', 'evokes', 'fear'],
  ['fog', 'collides', 'sun'],
  ['fog', 'collides', 'truth'],
  ['fog', 'transforms', 'silence'],
  ['fog', 'produces', 'silence'],
  ['fog', 'consumes', 'name'],
  ['fog', 'consumes', 'light'],
  ['fog', 'rhymes', 'mist'],
  ['fog', 'rhymes', 'ghost'],
  ['fog', 'rhymes', 'dream'],

  // ── Natural disasters ──
  ['earthquake', 'is', 'force'],
  ['earthquake', 'sound', 'roar'],
  ['earthquake', 'evokes', 'wrath'],
  ['earthquake', 'evokes', 'fear'],
  ['earthquake', 'collides', 'stone'],
  ['earthquake', 'collides', 'mountain'],
  ['earthquake', 'transforms', 'mountain'],
  ['earthquake', 'transforms', 'river'],
  ['earthquake', 'produces', 'dust'],
  ['earthquake', 'produces', 'pit'],
  ['earthquake', 'consumes', 'silence'],
  ['earthquake', 'rhymes', 'wrath'],
  ['earthquake', 'rhymes', 'bone'],

  ['typhoon', 'is', 'force'],
  ['typhoon', 'sound', 'roar'],
  ['typhoon', 'shape', 'spiral'],
  ['typhoon', 'evokes', 'rage'],
  ['typhoon', 'evokes', 'hunger'],
  ['typhoon', 'collides', 'ocean'],
  ['typhoon', 'collides', 'shore'],
  ['typhoon', 'transforms', 'ocean'],
  ['typhoon', 'transforms', 'shore'],
  ['typhoon', 'produces', 'rain'],
  ['typhoon', 'produces', 'flood'],
  ['typhoon', 'consumes', 'tree'],
  ['typhoon', 'consumes', 'silence'],
  ['typhoon', 'rhymes', 'serpent'],
  ['typhoon', 'rhymes', 'void'],

  ['storm', 'is', 'force'],
  ['storm', 'sound', 'roar'],
  ['storm', 'color', 'black'],
  ['storm', 'evokes', 'wrath'],
  ['storm', 'evokes', 'fear'],
  ['storm', 'collides', 'silence'],
  ['storm', 'collides', 'light'],
  ['storm', 'transforms', 'tree'],
  ['storm', 'produces', 'rain'],
  ['storm', 'produces', 'wind'],
  ['storm', 'produces', 'lightning'],
  ['storm', 'consumes', 'silence'],
  ['storm', 'rhymes', 'night'],
  ['storm', 'rhymes', 'wrath'],

  ['eruption', 'is', 'force'],
  ['eruption', 'color', 'red'],
  ['eruption', 'color', 'gold'],
  ['eruption', 'sound', 'roar'],
  ['eruption', 'evokes', 'rage'],
  ['eruption', 'evokes', 'wound'],
  ['eruption', 'collides', 'stone'],
  ['eruption', 'collides', 'ice'],
  ['eruption', 'transforms', 'mountain'],
  ['eruption', 'transforms', 'stone'],
  ['eruption', 'produces', 'fire'],
  ['eruption', 'produces', 'ash'],
  ['eruption', 'produces', 'smoke'],
  ['eruption', 'consumes', 'tree'],
  ['eruption', 'consumes', 'river'],
  ['eruption', 'rhymes', 'fire'],
  ['eruption', 'rhymes', 'blood'],

  ['meteor', 'is', 'celestial'],
  ['meteor', 'color', 'gold'],
  ['meteor', 'color', 'red'],
  ['meteor', 'shape', 'shard'],
  ['meteor', 'evokes', 'fate'],
  ['meteor', 'evokes', 'wrath'],
  ['meteor', 'collides', 'stone'],
  ['meteor', 'collides', 'ocean'],
  ['meteor', 'transforms', 'dust'],
  ['meteor', 'transforms', 'glass'],
  ['meteor', 'produces', 'fire'],
  ['meteor', 'produces', 'pit'],
  ['meteor', 'consumes', 'silence'],
  ['meteor', 'rhymes', 'star'],
  ['meteor', 'rhymes', 'wound'],

  ['flood', 'is', 'force'],
  ['flood', 'evokes', 'wrath'],
  ['flood', 'evokes', 'grief'],
  ['flood', 'collides', 'fire'],
  ['flood', 'collides', 'stone'],
  ['flood', 'transforms', 'river'],
  ['flood', 'transforms', 'shore'],
  ['flood', 'produces', 'soil'],
  ['flood', 'produces', 'silence'],
  ['flood', 'consumes', 'name'],
  ['flood', 'consumes', 'tomb'],
  ['flood', 'rhymes', 'blood'],
  ['flood', 'rhymes', 'tear'],

  ['lightning', 'is', 'force'],
  ['lightning', 'color', 'white'],
  ['lightning', 'shape', 'shard'],
  ['lightning', 'evokes', 'wrath'],
  ['lightning', 'evokes', 'truth'],
  ['lightning', 'collides', 'tree'],
  ['lightning', 'collides', 'stone'],
  ['lightning', 'transforms', 'tree'],
  ['lightning', 'transforms', 'glass'],
  ['lightning', 'produces', 'fire'],
  ['lightning', 'produces', 'light'],
  ['lightning', 'consumes', 'shadow'],
  ['lightning', 'rhymes', 'sword'],
  ['lightning', 'rhymes', 'wound'],

  // ── Landscape ──
  ['mountain', 'is', 'place'],
  ['mountain', 'evokes', 'endurance'],
  ['mountain', 'evokes', 'pride'],
  ['mountain', 'collides', 'sky'],
  ['mountain', 'transforms', 'stone'],
  ['mountain', 'produces', 'stone'],
  ['mountain', 'consumes', 'shadow'],
  ['mountain', 'rhymes', 'bone'],
  ['mountain', 'color', 'grey'],
  ['mountain', 'shape', 'pillar'],

  ['ocean', 'is', 'place'],
  ['ocean', 'evokes', 'longing'],
  ['ocean', 'evokes', 'hunger'],
  ['ocean', 'collides', 'shore'],
  ['ocean', 'transforms', 'stone'],
  ['ocean', 'produces', 'salt'],
  ['ocean', 'consumes', 'shore'],
  ['ocean', 'rhymes', 'void'],
  ['ocean', 'rhymes', 'memory'],
  ['ocean', 'color', 'blue'],
  ['ocean', 'sound', 'roar'],
  ['ocean', 'texture', 'wet'],

  ['river', 'is', 'place'],
  ['river', 'evokes', 'time'],
  ['river', 'evokes', 'memory'],
  ['river', 'collides', 'stone'],
  ['river', 'transforms', 'dust'],
  ['river', 'produces', 'soil'],
  ['river', 'consumes', 'stone'],
  ['river', 'rhymes', 'blood'],
  ['river', 'rhymes', 'vein'],
  ['river', 'color', 'blue'],
  ['river', 'sound', 'whisper'],

  ['cave', 'is', 'place'],
  ['cave', 'evokes', 'fear'],
  ['cave', 'evokes', 'memory'],
  ['cave', 'sound', 'echo'],
  ['cave', 'collides', 'light'],
  ['cave', 'collides', 'wind'],
  ['cave', 'produces', 'echo'],
  ['cave', 'transforms', 'tomb'],
  ['cave', 'consumes', 'sound'],
  ['cave', 'rhymes', 'womb'],
  ['cave', 'rhymes', 'mouth'],
  ['cave', 'color', 'black'],
  ['cave', 'texture', 'wet'],

  ['shore', 'is', 'place'],
  ['shore', 'evokes', 'longing'],
  ['shore', 'evokes', 'grief'],
  ['shore', 'collides', 'ocean'],
  ['shore', 'transforms', 'stone'],
  ['shore', 'produces', 'salt'],
  ['shore', 'consumes', 'stone'],
  ['shore', 'rhymes', 'wound'],
  ['shore', 'texture', 'rough'],
  ['shore', 'sound', 'whisper'],

  ['well', 'is', 'place'],
  ['well', 'shape', 'hollow'],
  ['well', 'evokes', 'memory'],
  ['well', 'evokes', 'truth'],
  ['well', 'collides', 'light'],
  ['well', 'produces', 'water'],
  ['well', 'transforms', 'mirror'],
  ['well', 'consumes', 'sound'],
  ['well', 'rhymes', 'void'],
  ['well', 'rhymes', 'eye'],
  ['well', 'color', 'black'],

  ['tomb', 'is', 'place'],
  ['tomb', 'evokes', 'silence'],
  ['tomb', 'evokes', 'memory'],
  ['tomb', 'collides', 'light'],
  ['tomb', 'produces', 'ghost'],
  ['tomb', 'transforms', 'dust'],
  ['tomb', 'consumes', 'name'],
  ['tomb', 'consumes', 'light'],
  ['tomb', 'rhymes', 'womb'],
  ['tomb', 'rhymes', 'moon'],
  ['tomb', 'rhymes', 'bone'],
  ['tomb', 'color', 'black'],
  ['tomb', 'texture', 'cold'],

  ['pit', 'is', 'place'],
  ['pit', 'shape', 'hollow'],
  ['pit', 'evokes', 'fear'],
  ['pit', 'evokes', 'hunger'],
  ['pit', 'collides', 'light'],
  ['pit', 'collides', 'stone'],
  ['pit', 'produces', 'echo'],
  ['pit', 'transforms', 'tomb'],
  ['pit', 'consumes', 'sound'],
  ['pit', 'rhymes', 'void'],
  ['pit', 'rhymes', 'night'],
  ['pit', 'color', 'black'],

  // ── Flora ──
  ['tree', 'is', 'flora'],
  ['tree', 'evokes', 'endurance'],
  ['tree', 'evokes', 'memory'],
  ['tree', 'collides', 'wind'],
  ['tree', 'collides', 'fire'],
  ['tree', 'transforms', 'ash'],
  ['tree', 'produces', 'shadow'],
  ['tree', 'produces', 'root'],
  ['tree', 'consumes', 'soil'],
  ['tree', 'rhymes', 'bone'],
  ['tree', 'rhymes', 'stone'],
  ['tree', 'color', 'green'],
  ['tree', 'texture', 'rough'],
  ['tree', 'shape', 'pillar'],

  ['flower', 'is', 'flora'],
  ['flower', 'color', 'red'],
  ['flower', 'evokes', 'longing'],
  ['flower', 'evokes', 'grief'],
  ['flower', 'collides', 'frost'],
  ['flower', 'transforms', 'dust'],
  ['flower', 'produces', 'seed'],
  ['flower', 'rhymes', 'wound'],
  ['flower', 'rhymes', 'blood'],
  ['flower', 'texture', 'soft'],
  ['flower', 'shape', 'circle'],

  ['vine', 'is', 'flora'],
  ['vine', 'evokes', 'hunger'],
  ['vine', 'evokes', 'patience'],
  ['vine', 'collides', 'stone'],
  ['vine', 'collides', 'light'],
  ['vine', 'transforms', 'thread'],
  ['vine', 'produces', 'shadow'],
  ['vine', 'consumes', 'stone'],
  ['vine', 'rhymes', 'serpent'],
  ['vine', 'rhymes', 'river'],
  ['vine', 'rhymes', 'vein'],
  ['vine', 'color', 'green'],
  ['vine', 'texture', 'rough'],
  ['vine', 'shape', 'coil'],

  ['moss', 'is', 'flora'],
  ['moss', 'color', 'grey'],
  ['moss', 'texture', 'smooth'],
  ['moss', 'evokes', 'silence'],
  ['moss', 'evokes', 'memory'],
  ['moss', 'produces', 'soil'],
  ['moss', 'consumes', 'stone'],
  ['moss', 'transforms', 'soil'],
  ['moss', 'rhymes', 'ash'],
  ['moss', 'rhymes', 'dust'],
  ['moss', 'shape', 'slab'],

  ['root', 'is', 'flora'],
  ['root', 'evokes', 'endurance'],
  ['root', 'evokes', 'hunger'],
  ['root', 'collides', 'stone'],
  ['root', 'transforms', 'soil'],
  ['root', 'produces', 'wound'],
  ['root', 'consumes', 'soil'],
  ['root', 'rhymes', 'vein'],
  ['root', 'rhymes', 'bone'],
  ['root', 'color', 'brown'],
  ['root', 'texture', 'rough'],
  ['root', 'shape', 'coil'],

  // ── Fauna ──
  ['serpent', 'is', 'fauna'],
  ['serpent', 'shape', 'spiral'],
  ['serpent', 'evokes', 'lie'],
  ['serpent', 'evokes', 'wisdom'],
  ['serpent', 'collides', 'truth'],
  ['serpent', 'transforms', 'ash'],
  ['serpent', 'produces', 'wound'],
  ['serpent', 'consumes', 'flesh'],
  ['serpent', 'rhymes', 'river'],
  ['serpent', 'rhymes', 'vine'],
  ['serpent', 'color', 'green'],
  ['serpent', 'texture', 'smooth'],
  ['serpent', 'shape', 'coil'],
  ['serpent', 'sound', 'hush'],

  ['crow', 'is', 'fauna'],
  ['crow', 'color', 'black'],
  ['crow', 'evokes', 'death'],
  ['crow', 'evokes', 'memory'],
  ['crow', 'collides', 'silence'],
  ['crow', 'collides', 'light'],
  ['crow', 'transforms', 'omen'],
  ['crow', 'produces', 'sound'],
  ['crow', 'consumes', 'seed'],
  ['crow', 'rhymes', 'shadow'],
  ['crow', 'sound', 'rasp'],

  ['spider', 'is', 'fauna'],
  ['spider', 'shape', 'web'],
  ['spider', 'evokes', 'patience'],
  ['spider', 'evokes', 'trap'],
  ['spider', 'collides', 'wind'],
  ['spider', 'transforms', 'fate'],
  ['spider', 'produces', 'thread'],
  ['spider', 'consumes', 'silence'],
  ['spider', 'rhymes', 'hand'],
  ['spider', 'color', 'black'],
  ['spider', 'texture', 'sharp'],
  ['spider', 'sound', 'hush'],

  ['moth', 'is', 'fauna'],
  ['moth', 'color', 'grey'],
  ['moth', 'evokes', 'longing'],
  ['moth', 'evokes', 'death'],
  ['moth', 'collides', 'light'],
  ['moth', 'transforms', 'ash'],
  ['moth', 'produces', 'dust'],
  ['moth', 'consumes', 'light'],
  ['moth', 'rhymes', 'ash'],
  ['moth', 'rhymes', 'dream'],
  ['moth', 'sound', 'hush'],

  ['ghost', 'is', 'fauna'],
  ['ghost', 'evokes', 'memory'],
  ['ghost', 'evokes', 'grief'],
  ['ghost', 'collides', 'light'],
  ['ghost', 'collides', 'silence'],
  ['ghost', 'transforms', 'silence'],
  ['ghost', 'produces', 'cold'],
  ['ghost', 'rhymes', 'echo'],
  ['ghost', 'rhymes', 'mist'],
  ['ghost', 'color', 'white'],
  ['ghost', 'texture', 'cold'],

  ['worm', 'is', 'fauna'],
  ['worm', 'evokes', 'death'],
  ['worm', 'evokes', 'patience'],
  ['worm', 'collides', 'bone'],
  ['worm', 'transforms', 'bone'],
  ['worm', 'produces', 'soil'],
  ['worm', 'consumes', 'flesh'],
  ['worm', 'consumes', 'soil'],
  ['worm', 'rhymes', 'root'],
  ['worm', 'rhymes', 'river'],
  ['worm', 'color', 'brown'],
  ['worm', 'texture', 'wet'],

  ['wolf', 'is', 'fauna'],
  ['wolf', 'color', 'grey'],
  ['wolf', 'sound', 'roar'],
  ['wolf', 'evokes', 'hunger'],
  ['wolf', 'evokes', 'fear'],
  ['wolf', 'collides', 'silence'],
  ['wolf', 'produces', 'wound'],
  ['wolf', 'transforms', 'ghost'],
  ['wolf', 'consumes', 'flesh'],
  ['wolf', 'rhymes', 'moon'],
  ['wolf', 'rhymes', 'shadow'],

  // ── Items ──
  ['sword', 'is', 'item'],
  ['sword', 'color', 'grey'],
  ['sword', 'texture', 'smooth'],
  ['sword', 'shape', 'shard'],
  ['sword', 'evokes', 'will'],
  ['sword', 'evokes', 'death'],
  ['sword', 'collides', 'flesh'],
  ['sword', 'produces', 'wound'],
  ['sword', 'produces', 'blood'],
  ['sword', 'transforms', 'rust'],
  ['sword', 'consumes', 'life'],
  ['sword', 'rhymes', 'bone'],
  ['sword', 'rhymes', 'wound'],

  ['knife', 'is', 'item'],
  ['knife', 'color', 'grey'],
  ['knife', 'evokes', 'hunger'],
  ['knife', 'evokes', 'sacrifice'],
  ['knife', 'collides', 'flesh'],
  ['knife', 'produces', 'wound'],
  ['knife', 'produces', 'blood'],
  ['knife', 'transforms', 'rust'],
  ['knife', 'consumes', 'trust'],
  ['knife', 'rhymes', 'bone'],
  ['knife', 'rhymes', 'ice'],

  ['plow', 'is', 'item'],
  ['plow', 'evokes', 'endurance'],
  ['plow', 'evokes', 'will'],
  ['plow', 'collides', 'stone'],
  ['plow', 'transforms', 'soil'],
  ['plow', 'produces', 'soil'],
  ['plow', 'color', 'grey'],
  ['plow', 'consumes', 'time'],
  ['plow', 'rhymes', 'wound'],
  ['plow', 'rhymes', 'bone'],

  ['bowl', 'is', 'item'],
  ['bowl', 'color', 'brown'],
  ['bowl', 'shape', 'hollow'],
  ['bowl', 'transforms', 'dust'],
  ['bowl', 'evokes', 'hunger'],
  ['bowl', 'evokes', 'longing'],
  ['bowl', 'collides', 'void'],
  ['bowl', 'produces', 'tear'],
  ['bowl', 'consumes', 'water'],
  ['bowl', 'consumes', 'blood'],
  ['bowl', 'rhymes', 'moon'],
  ['bowl', 'rhymes', 'eye'],

  ['furnace', 'is', 'item'],
  ['furnace', 'color', 'gold'],
  ['furnace', 'evokes', 'hunger'],
  ['furnace', 'evokes', 'will'],
  ['furnace', 'collides', 'stone'],
  ['furnace', 'transforms', 'iron'],
  ['furnace', 'produces', 'smoke'],
  ['furnace', 'produces', 'ash'],
  ['furnace', 'consumes', 'iron'],
  ['furnace', 'consumes', 'bone'],
  ['furnace', 'rhymes', 'fire'],
  ['furnace', 'rhymes', 'hunger'],

  ['mask', 'is', 'item'],
  ['mask', 'color', 'white'],
  ['mask', 'evokes', 'lie'],
  ['mask', 'evokes', 'truth'],
  ['mask', 'collides', 'truth'],
  ['mask', 'collides', 'wound'],
  ['mask', 'transforms', 'name'],
  ['mask', 'produces', 'fear'],
  ['mask', 'consumes', 'truth'],
  ['mask', 'rhymes', 'shadow'],
  ['mask', 'rhymes', 'dream'],

  // ── New places ──
  ['desert', 'is', 'place'],
  ['desert', 'color', 'gold'],
  ['desert', 'texture', 'rough'],
  ['desert', 'evokes', 'hunger'],
  ['desert', 'evokes', 'patience'],
  ['desert', 'collides', 'water'],
  ['desert', 'transforms', 'dust'],
  ['desert', 'consumes', 'rain'],
  ['desert', 'produces', 'dust'],
  ['desert', 'rhymes', 'silence'],
  ['desert', 'rhymes', 'bone'],

  ['lake', 'is', 'place'],
  ['lake', 'color', 'silver'],
  ['lake', 'sound', 'hush'],
  ['lake', 'texture', 'smooth'],
  ['lake', 'evokes', 'memory'],
  ['lake', 'evokes', 'grief'],
  ['lake', 'collides', 'fire'],
  ['lake', 'produces', 'mist'],
  ['lake', 'transforms', 'swamp'],
  ['lake', 'produces', 'reflection'],
  ['lake', 'rhymes', 'eye'],
  ['lake', 'rhymes', 'moon'],

  ['cliff', 'is', 'place'],
  ['cliff', 'shape', 'shard'],
  ['cliff', 'texture', 'rough'],
  ['cliff', 'evokes', 'fall'],
  ['cliff', 'evokes', 'fear'],
  ['cliff', 'collides', 'wind'],
  ['cliff', 'transforms', 'dust'],
  ['cliff', 'produces', 'echo'],
  ['cliff', 'rhymes', 'wound'],
  ['cliff', 'rhymes', 'sword'],
  ['cliff', 'color', 'grey'],

  ['ruins', 'is', 'place'],
  ['ruins', 'color', 'grey'],
  ['ruins', 'texture', 'crumbling'],
  ['ruins', 'evokes', 'memory'],
  ['ruins', 'evokes', 'grief'],
  ['ruins', 'collides', 'time'],
  ['ruins', 'transforms', 'dust'],
  ['ruins', 'consumes', 'name'],
  ['ruins', 'produces', 'dust'],
  ['ruins', 'produces', 'ghost'],
  ['ruins', 'rhymes', 'bone'],
  ['ruins', 'rhymes', 'tomb'],

  ['threshold', 'is', 'place'],
  ['threshold', 'shape', 'arch'],
  ['threshold', 'evokes', 'fear'],
  ['threshold', 'evokes', 'longing'],
  ['threshold', 'collides', 'sleep'],
  ['threshold', 'transforms', 'fate'],
  ['threshold', 'produces', 'echo'],
  ['threshold', 'rhymes', 'dawn'],
  ['threshold', 'rhymes', 'wound'],
  ['threshold', 'color', 'grey'],

  // ── New items ──
  ['net', 'is', 'item'],
  ['net', 'color', 'white'],
  ['net', 'shape', 'web'],
  ['net', 'evokes', 'fate'],
  ['net', 'evokes', 'hunger'],
  ['net', 'collides', 'wind'],
  ['net', 'transforms', 'thread'],
  ['net', 'consumes', 'freedom'],
  ['net', 'produces', 'snare'],
  ['net', 'rhymes', 'spider'],
  ['net', 'rhymes', 'vine'],

  ['needle', 'is', 'item'],
  ['needle', 'color', 'silver'],
  ['needle', 'shape', 'thorn'],
  ['needle', 'evokes', 'pain'],
  ['needle', 'evokes', 'precision'],
  ['needle', 'collides', 'flesh'],
  ['needle', 'transforms', 'wound'],
  ['needle', 'produces', 'thread'],
  ['needle', 'consumes', 'thread'],
  ['needle', 'rhymes', 'star'],
  ['needle', 'rhymes', 'tooth'],

  ['bell', 'is', 'item'],
  ['bell', 'shape', 'dome'],
  ['bell', 'sound', 'ring'],
  ['bell', 'color', 'silver'],
  ['bell', 'evokes', 'memory'],
  ['bell', 'evokes', 'warning'],
  ['bell', 'transforms', 'silence'],
  ['bell', 'collides', 'silence'],
  ['bell', 'produces', 'echo'],
  ['bell', 'produces', 'song'],
  ['bell', 'rhymes', 'moon'],
  ['bell', 'rhymes', 'bowl'],

  ['staff', 'is', 'item'],
  ['staff', 'shape', 'pillar'],
  ['staff', 'texture', 'smooth'],
  ['staff', 'evokes', 'wisdom'],
  ['staff', 'evokes', 'authority'],
  ['staff', 'collides', 'serpent'],
  ['staff', 'transforms', 'path'],
  ['staff', 'produces', 'root'],
  ['staff', 'rhymes', 'tree'],
  ['staff', 'rhymes', 'bone'],

  ['mirror', 'is', 'item'],
  ['mirror', 'color', 'silver'],
  ['mirror', 'texture', 'smooth'],
  ['mirror', 'evokes', 'truth'],
  ['mirror', 'evokes', 'vanity'],
  ['mirror', 'collides', 'shadow'],
  ['mirror', 'collides', 'lie'],
  ['mirror', 'transforms', 'truth'],
  ['mirror', 'produces', 'reflection'],
  ['mirror', 'rhymes', 'lake'],
  ['mirror', 'rhymes', 'eye'],

  // ── New fauna ──
  ['whale', 'is', 'fauna'],
  ['whale', 'color', 'grey'],
  ['whale', 'sound', 'moan'],
  ['whale', 'texture', 'smooth'],
  ['whale', 'evokes', 'longing'],
  ['whale', 'evokes', 'memory'],
  ['whale', 'collides', 'shore'],
  ['whale', 'transforms', 'ocean'],
  ['whale', 'produces', 'song'],
  ['whale', 'rhymes', 'moon'],

  ['owl', 'is', 'fauna'],
  ['owl', 'color', 'white'],
  ['owl', 'sound', 'hush'],
  ['owl', 'evokes', 'wisdom'],
  ['owl', 'evokes', 'death'],
  ['owl', 'collides', 'sun'],
  ['owl', 'transforms', 'night'],
  ['owl', 'produces', 'fear'],
  ['owl', 'consumes', 'silence'],
  ['owl', 'rhymes', 'moon'],
  ['owl', 'rhymes', 'ghost'],

  ['beetle', 'is', 'fauna'],
  ['beetle', 'color', 'black'],
  ['beetle', 'texture', 'glossy'],
  ['beetle', 'evokes', 'patience'],
  ['beetle', 'evokes', 'death'],
  ['beetle', 'collides', 'fire'],
  ['beetle', 'transforms', 'soil'],
  ['beetle', 'consumes', 'flesh'],
  ['beetle', 'produces', 'dust'],
  ['beetle', 'rhymes', 'worm'],

  // ── Multi-category edges (existing concepts usable as tools) ──
  ['well', 'is', 'item'],
  ['tomb', 'is', 'item'],
  ['vine', 'is', 'item'],
  ['bone', 'is', 'item'],
  ['hand', 'is', 'item'],
  ['skull', 'is', 'item'],

  // ══════════════════════════════════════════════════════════════════════
  // Phase 14 — Graph Expansion
  // ══════════════════════════════════════════════════════════════════════

  // ── Promoted Phantoms — Forces ──

  ['hope', 'is', 'force'],
  ['hope', 'color', 'gold'],
  ['hope', 'texture', 'warm'],
  ['hope', 'evokes', 'light'],
  ['hope', 'evokes', 'breath'],
  ['hope', 'collides', 'void'],
  ['hope', 'collides', 'grief'],
  ['hope', 'transforms', 'dream'],
  ['hope', 'produces', 'song'],
  ['hope', 'rhymes', 'dawn'],
  ['hope', 'rhymes', 'seed'],
  ['hope', 'sound', 'ring'],

  ['joy', 'is', 'force'],
  ['joy', 'color', 'gold'],
  ['joy', 'sound', 'ring'],
  ['joy', 'evokes', 'light'],
  ['joy', 'evokes', 'song'],
  ['joy', 'collides', 'grief'],
  ['joy', 'collides', 'silence'],
  ['joy', 'transforms', 'memory'],
  ['joy', 'produces', 'tear'],
  ['joy', 'rhymes', 'bell'],
  ['joy', 'rhymes', 'flower'],

  ['pride', 'is', 'force'],
  ['pride', 'color', 'gold'],
  ['pride', 'texture', 'smooth'],
  ['pride', 'evokes', 'sun'],
  ['pride', 'evokes', 'fire'],
  ['pride', 'collides', 'dust'],
  ['pride', 'collides', 'ash'],
  ['pride', 'transforms', 'wrath'],
  ['pride', 'produces', 'mask'],
  ['pride', 'rhymes', 'gold'],
  ['pride', 'rhymes', 'mountain'],
  ['pride', 'sound', 'roar'],

  ['patience', 'is', 'force'],
  ['patience', 'color', 'grey'],
  ['patience', 'texture', 'smooth'],
  ['patience', 'evokes', 'stone'],
  ['patience', 'evokes', 'root'],
  ['patience', 'collides', 'rage'],
  ['patience', 'transforms', 'wisdom'],
  ['patience', 'produces', 'root'],
  ['patience', 'consumes', 'hunger'],
  ['patience', 'rhymes', 'river'],
  ['patience', 'rhymes', 'moss'],
  ['patience', 'sound', 'hush'],

  ['trust', 'is', 'force'],
  ['trust', 'color', 'clear'],
  ['trust', 'texture', 'smooth'],
  ['trust', 'evokes', 'light'],
  ['trust', 'evokes', 'hand'],
  ['trust', 'collides', 'lie'],
  ['trust', 'collides', 'fear'],
  ['trust', 'transforms', 'grief'],
  ['trust', 'produces', 'wound'],
  ['trust', 'rhymes', 'glass'],
  ['trust', 'rhymes', 'bone'],

  ['creation', 'is', 'force'],
  ['creation', 'color', 'white'],
  ['creation', 'sound', 'crack'],
  ['creation', 'evokes', 'light'],
  ['creation', 'evokes', 'wound'],
  ['creation', 'collides', 'void'],
  ['creation', 'collides', 'death'],
  ['creation', 'transforms', 'void'],
  ['creation', 'produces', 'light'],
  ['creation', 'rhymes', 'dawn'],
  ['creation', 'rhymes', 'seed'],

  ['warmth', 'is', 'force'],
  ['warmth', 'color', 'gold'],
  ['warmth', 'texture', 'soft'],
  ['warmth', 'evokes', 'life'],
  ['warmth', 'evokes', 'memory'],
  ['warmth', 'collides', 'void'],
  ['warmth', 'collides', 'ice'],
  ['warmth', 'transforms', 'seed'],
  ['warmth', 'produces', 'mist'],
  ['warmth', 'rhymes', 'breath'],
  ['warmth', 'rhymes', 'sun'],

  ['cold', 'is', 'force'],
  ['cold', 'color', 'blue'],
  ['cold', 'texture', 'sharp'],
  ['cold', 'evokes', 'death'],
  ['cold', 'evokes', 'silence'],
  ['cold', 'collides', 'fire'],
  ['cold', 'collides', 'warmth'],
  ['cold', 'transforms', 'ice'],
  ['cold', 'produces', 'frost'],
  ['cold', 'consumes', 'breath'],
  ['cold', 'rhymes', 'stone'],
  ['cold', 'rhymes', 'bone'],

  ['omen', 'is', 'force'],
  ['omen', 'color', 'black'],
  ['omen', 'sound', 'whisper'],
  ['omen', 'evokes', 'fear'],
  ['omen', 'evokes', 'fate'],
  ['omen', 'collides', 'truth'],
  ['omen', 'transforms', 'fear'],
  ['omen', 'produces', 'silence'],
  ['omen', 'rhymes', 'shadow'],
  ['omen', 'rhymes', 'crow'],

  ['reflection', 'is', 'force'],
  ['reflection', 'color', 'silver'],
  ['reflection', 'texture', 'smooth'],
  ['reflection', 'evokes', 'truth'],
  ['reflection', 'evokes', 'memory'],
  ['reflection', 'collides', 'shadow'],
  ['reflection', 'transforms', 'truth'],
  ['reflection', 'produces', 'grief'],
  ['reflection', 'rhymes', 'mirror'],
  ['reflection', 'rhymes', 'lake'],

  // ── Promoted Phantoms — Material / Body / Flora ──

  ['scar', 'is', 'material'],
  ['scar', 'color', 'red'],
  ['scar', 'texture', 'rough'],
  ['scar', 'evokes', 'memory'],
  ['scar', 'evokes', 'endurance'],
  ['scar', 'collides', 'time'],
  ['scar', 'transforms', 'memory'],
  ['scar', 'produces', 'story'],
  ['scar', 'rhymes', 'wound'],
  ['scar', 'rhymes', 'stone'],

  ['thorn', 'is', 'flora'],
  ['thorn', 'color', 'brown'],
  ['thorn', 'shape', 'point'],
  ['thorn', 'texture', 'sharp'],
  ['thorn', 'evokes', 'wound'],
  ['thorn', 'evokes', 'endurance'],
  ['thorn', 'collides', 'flesh'],
  ['thorn', 'transforms', 'wound'],
  ['thorn', 'produces', 'blood'],
  ['thorn', 'consumes', 'hand'],
  ['thorn', 'rhymes', 'needle'],
  ['thorn', 'rhymes', 'bone'],

  ['tooth', 'is', 'body'],
  ['tooth', 'color', 'white'],
  ['tooth', 'shape', 'point'],
  ['tooth', 'texture', 'smooth'],
  ['tooth', 'evokes', 'hunger'],
  ['tooth', 'evokes', 'death'],
  ['tooth', 'collides', 'bone'],
  ['tooth', 'transforms', 'dust'],
  ['tooth', 'produces', 'wound'],
  ['tooth', 'consumes', 'flesh'],
  ['tooth', 'rhymes', 'needle'],
  ['tooth', 'rhymes', 'star'],
  ['tooth', 'sound', 'crack'],

  // ── New Forces ──

  ['mercy', 'is', 'force'],
  ['mercy', 'color', 'white'],
  ['mercy', 'texture', 'soft'],
  ['mercy', 'evokes', 'water'],
  ['mercy', 'evokes', 'tear'],
  ['mercy', 'collides', 'wrath'],
  ['mercy', 'collides', 'hunger'],
  ['mercy', 'transforms', 'wound'],
  ['mercy', 'produces', 'silence'],
  ['mercy', 'rhymes', 'rain'],
  ['mercy', 'rhymes', 'snow'],
  ['mercy', 'sound', 'whisper'],

  ['greed', 'is', 'force'],
  ['greed', 'color', 'gold'],
  ['greed', 'texture', 'sticky'],
  ['greed', 'evokes', 'hunger'],
  ['greed', 'evokes', 'fire'],
  ['greed', 'collides', 'ash'],
  ['greed', 'collides', 'mercy'],
  ['greed', 'transforms', 'hunger'],
  ['greed', 'produces', 'ruin'],
  ['greed', 'consumes', 'trust'],
  ['greed', 'rhymes', 'rust'],
  ['greed', 'rhymes', 'furnace'],

  ['betrayal', 'is', 'force'],
  ['betrayal', 'color', 'black'],
  ['betrayal', 'texture', 'sharp'],
  ['betrayal', 'evokes', 'wound'],
  ['betrayal', 'evokes', 'silence'],
  ['betrayal', 'collides', 'trust'],
  ['betrayal', 'transforms', 'trust'],
  ['betrayal', 'produces', 'grief'],
  ['betrayal', 'consumes', 'name'],
  ['betrayal', 'rhymes', 'knife'],
  ['betrayal', 'rhymes', 'shadow'],
  ['betrayal', 'sound', 'crack'],

  ['envy', 'is', 'force'],
  ['envy', 'color', 'green'],
  ['envy', 'texture', 'sharp'],
  ['envy', 'evokes', 'hunger'],
  ['envy', 'evokes', 'shadow'],
  ['envy', 'collides', 'joy'],
  ['envy', 'transforms', 'rage'],
  ['envy', 'produces', 'lie'],
  ['envy', 'consumes', 'joy'],
  ['envy', 'rhymes', 'serpent'],
  ['envy', 'rhymes', 'mirror'],
  ['envy', 'sound', 'whisper'],

  ['shame', 'is', 'force'],
  ['shame', 'color', 'red'],
  ['shame', 'texture', 'rough'],
  ['shame', 'evokes', 'fire'],
  ['shame', 'evokes', 'wound'],
  ['shame', 'collides', 'pride'],
  ['shame', 'transforms', 'silence'],
  ['shame', 'produces', 'mask'],
  ['shame', 'consumes', 'name'],
  ['shame', 'rhymes', 'ash'],
  ['shame', 'rhymes', 'flame'],
  ['shame', 'sound', 'hush'],

  ['devotion', 'is', 'force'],
  ['devotion', 'color', 'gold'],
  ['devotion', 'texture', 'warm'],
  ['devotion', 'evokes', 'fire'],
  ['devotion', 'evokes', 'song'],
  ['devotion', 'collides', 'death'],
  ['devotion', 'transforms', 'sacrifice'],
  ['devotion', 'produces', 'song'],
  ['devotion', 'consumes', 'will'],
  ['devotion', 'rhymes', 'flame'],
  ['devotion', 'rhymes', 'thread'],

  ['ruin', 'is', 'force'],
  ['ruin', 'color', 'grey'],
  ['ruin', 'texture', 'crumbling'],
  ['ruin', 'evokes', 'time'],
  ['ruin', 'evokes', 'grief'],
  ['ruin', 'collides', 'creation'],
  ['ruin', 'transforms', 'dust'],
  ['ruin', 'produces', 'silence'],
  ['ruin', 'consumes', 'name'],
  ['ruin', 'rhymes', 'ash'],
  ['ruin', 'rhymes', 'tomb'],

  ['madness', 'is', 'force'],
  ['madness', 'color', 'varied'],
  ['madness', 'sound', 'wail'],
  ['madness', 'evokes', 'dream'],
  ['madness', 'evokes', 'void'],
  ['madness', 'collides', 'truth'],
  ['madness', 'collides', 'wisdom'],
  ['madness', 'transforms', 'truth'],
  ['madness', 'produces', 'shadow'],
  ['madness', 'consumes', 'memory'],
  ['madness', 'rhymes', 'storm'],
  ['madness', 'rhymes', 'dream'],

  ['desire', 'is', 'force'],
  ['desire', 'color', 'red'],
  ['desire', 'texture', 'warm'],
  ['desire', 'evokes', 'fire'],
  ['desire', 'evokes', 'hunger'],
  ['desire', 'collides', 'silence'],
  ['desire', 'collides', 'death'],
  ['desire', 'transforms', 'longing'],
  ['desire', 'produces', 'wound'],
  ['desire', 'consumes', 'patience'],
  ['desire', 'rhymes', 'flame'],
  ['desire', 'rhymes', 'moon'],
  ['desire', 'sound', 'whisper'],

  ['prophecy', 'is', 'force'],
  ['prophecy', 'color', 'silver'],
  ['prophecy', 'sound', 'whisper'],
  ['prophecy', 'evokes', 'fate'],
  ['prophecy', 'evokes', 'fear'],
  ['prophecy', 'collides', 'lie'],
  ['prophecy', 'transforms', 'fate'],
  ['prophecy', 'produces', 'fear'],
  ['prophecy', 'consumes', 'silence'],
  ['prophecy', 'rhymes', 'echo'],
  ['prophecy', 'rhymes', 'star'],

  ['vengeance', 'is', 'force'],
  ['vengeance', 'color', 'red'],
  ['vengeance', 'sound', 'roar'],
  ['vengeance', 'evokes', 'fire'],
  ['vengeance', 'evokes', 'wound'],
  ['vengeance', 'collides', 'mercy'],
  ['vengeance', 'collides', 'silence'],
  ['vengeance', 'transforms', 'rage'],
  ['vengeance', 'produces', 'blood'],
  ['vengeance', 'consumes', 'mercy'],
  ['vengeance', 'rhymes', 'sword'],
  ['vengeance', 'rhymes', 'storm'],

  ['despair', 'is', 'force'],
  ['despair', 'color', 'black'],
  ['despair', 'texture', 'cold'],
  ['despair', 'evokes', 'void'],
  ['despair', 'evokes', 'silence'],
  ['despair', 'collides', 'hope'],
  ['despair', 'collides', 'light'],
  ['despair', 'transforms', 'silence'],
  ['despair', 'produces', 'dust'],
  ['despair', 'consumes', 'song'],
  ['despair', 'rhymes', 'void'],
  ['despair', 'rhymes', 'ash'],

  // ── New Materials ──

  ['clay', 'is', 'material'],
  ['clay', 'color', 'brown'],
  ['clay', 'texture', 'wet'],
  ['clay', 'shape', 'hollow'],
  ['clay', 'evokes', 'creation'],
  ['clay', 'evokes', 'patience'],
  ['clay', 'collides', 'fire'],
  ['clay', 'transforms', 'stone'],
  ['clay', 'produces', 'bowl'],
  ['clay', 'consumes', 'water'],
  ['clay', 'rhymes', 'soil'],
  ['clay', 'rhymes', 'flesh'],

  ['amber', 'is', 'material'],
  ['amber', 'color', 'gold'],
  ['amber', 'texture', 'smooth'],
  ['amber', 'evokes', 'time'],
  ['amber', 'evokes', 'memory'],
  ['amber', 'collides', 'fire'],
  ['amber', 'transforms', 'light'],
  ['amber', 'produces', 'warmth'],
  ['amber', 'consumes', 'time'],
  ['amber', 'rhymes', 'honey'],
  ['amber', 'rhymes', 'sun'],
  ['amber', 'sound', 'ring'],

  ['obsidian', 'is', 'material'],
  ['obsidian', 'color', 'black'],
  ['obsidian', 'texture', 'smooth'],
  ['obsidian', 'shape', 'shard'],
  ['obsidian', 'evokes', 'truth'],
  ['obsidian', 'evokes', 'wrath'],
  ['obsidian', 'collides', 'light'],
  ['obsidian', 'transforms', 'knife'],
  ['obsidian', 'produces', 'shard'],
  ['obsidian', 'rhymes', 'glass'],
  ['obsidian', 'rhymes', 'night'],
  ['obsidian', 'sound', 'crack'],

  ['silk', 'is', 'material'],
  ['silk', 'color', 'white'],
  ['silk', 'texture', 'soft'],
  ['silk', 'evokes', 'dream'],
  ['silk', 'evokes', 'vanity'],
  ['silk', 'collides', 'fire'],
  ['silk', 'transforms', 'ash'],
  ['silk', 'produces', 'thread'],
  ['silk', 'rhymes', 'mist'],
  ['silk', 'rhymes', 'moon'],

  ['venom', 'is', 'material'],
  ['venom', 'color', 'green'],
  ['venom', 'texture', 'wet'],
  ['venom', 'evokes', 'betrayal'],
  ['venom', 'evokes', 'death'],
  ['venom', 'collides', 'blood'],
  ['venom', 'transforms', 'flesh'],
  ['venom', 'produces', 'wound'],
  ['venom', 'consumes', 'life'],
  ['venom', 'rhymes', 'serpent'],
  ['venom', 'rhymes', 'rain'],
  ['venom', 'sound', 'hush'],

  ['honey', 'is', 'material'],
  ['honey', 'color', 'gold'],
  ['honey', 'texture', 'sticky'],
  ['honey', 'evokes', 'patience'],
  ['honey', 'evokes', 'desire'],
  ['honey', 'collides', 'ash'],
  ['honey', 'transforms', 'wax'],
  ['honey', 'produces', 'warmth'],
  ['honey', 'rhymes', 'amber'],
  ['honey', 'rhymes', 'sun'],

  ['copper', 'is', 'material'],
  ['copper', 'color', 'red'],
  ['copper', 'texture', 'smooth'],
  ['copper', 'evokes', 'endurance'],
  ['copper', 'evokes', 'time'],
  ['copper', 'collides', 'rust'],
  ['copper', 'transforms', 'rust'],
  ['copper', 'produces', 'ring'],
  ['copper', 'rhymes', 'blood'],
  ['copper', 'rhymes', 'iron'],
  ['copper', 'sound', 'ring'],

  ['pearl', 'is', 'material'],
  ['pearl', 'color', 'white'],
  ['pearl', 'texture', 'smooth'],
  ['pearl', 'shape', 'circle'],
  ['pearl', 'evokes', 'grief'],
  ['pearl', 'evokes', 'patience'],
  ['pearl', 'collides', 'dust'],
  ['pearl', 'transforms', 'tear'],
  ['pearl', 'produces', 'light'],
  ['pearl', 'rhymes', 'moon'],
  ['pearl', 'rhymes', 'tear'],

  ['tar', 'is', 'material'],
  ['tar', 'color', 'black'],
  ['tar', 'texture', 'sticky'],
  ['tar', 'evokes', 'death'],
  ['tar', 'evokes', 'hunger'],
  ['tar', 'collides', 'water'],
  ['tar', 'transforms', 'stone'],
  ['tar', 'produces', 'shadow'],
  ['tar', 'consumes', 'light'],
  ['tar', 'consumes', 'breath'],
  ['tar', 'rhymes', 'void'],
  ['tar', 'rhymes', 'blood'],
  ['tar', 'sound', 'hum'],

  ['soot', 'is', 'material'],
  ['soot', 'color', 'black'],
  ['soot', 'texture', 'rough'],
  ['soot', 'evokes', 'grief'],
  ['soot', 'evokes', 'memory'],
  ['soot', 'collides', 'snow'],
  ['soot', 'transforms', 'dust'],
  ['soot', 'produces', 'shadow'],
  ['soot', 'rhymes', 'ash'],
  ['soot', 'rhymes', 'night'],

  // ── New Body ──

  ['tongue', 'is', 'body'],
  ['tongue', 'color', 'red'],
  ['tongue', 'texture', 'wet'],
  ['tongue', 'evokes', 'lie'],
  ['tongue', 'evokes', 'truth'],
  ['tongue', 'collides', 'silence'],
  ['tongue', 'transforms', 'song'],
  ['tongue', 'produces', 'name'],
  ['tongue', 'produces', 'song'],
  ['tongue', 'consumes', 'silence'],
  ['tongue', 'rhymes', 'mouth'],
  ['tongue', 'rhymes', 'flame'],

  ['rib', 'is', 'body'],
  ['rib', 'color', 'white'],
  ['rib', 'shape', 'arch'],
  ['rib', 'texture', 'smooth'],
  ['rib', 'evokes', 'shelter'],
  ['rib', 'evokes', 'wound'],
  ['rib', 'collides', 'stone'],
  ['rib', 'transforms', 'bone'],
  ['rib', 'produces', 'echo'],
  ['rib', 'rhymes', 'cave'],
  ['rib', 'rhymes', 'bone'],

  ['spine', 'is', 'body'],
  ['spine', 'color', 'white'],
  ['spine', 'shape', 'pillar'],
  ['spine', 'texture', 'rough'],
  ['spine', 'evokes', 'endurance'],
  ['spine', 'evokes', 'will'],
  ['spine', 'collides', 'wind'],
  ['spine', 'transforms', 'bone'],
  ['spine', 'produces', 'dust'],
  ['spine', 'rhymes', 'mountain'],
  ['spine', 'rhymes', 'tree'],

  ['marrow', 'is', 'body'],
  ['marrow', 'color', 'gold'],
  ['marrow', 'texture', 'wet'],
  ['marrow', 'evokes', 'life'],
  ['marrow', 'evokes', 'hunger'],
  ['marrow', 'collides', 'death'],
  ['marrow', 'transforms', 'blood'],
  ['marrow', 'produces', 'life'],
  ['marrow', 'consumes', 'bone'],
  ['marrow', 'rhymes', 'honey'],
  ['marrow', 'rhymes', 'seed'],
  ['marrow', 'sound', 'hum'],

  ['heart', 'is', 'body'],
  ['heart', 'color', 'red'],
  ['heart', 'sound', 'drum'],
  ['heart', 'texture', 'wet'],
  ['heart', 'evokes', 'devotion'],
  ['heart', 'evokes', 'fear'],
  ['heart', 'collides', 'stone'],
  ['heart', 'collides', 'silence'],
  ['heart', 'transforms', 'blood'],
  ['heart', 'produces', 'blood'],
  ['heart', 'consumes', 'silence'],
  ['heart', 'rhymes', 'fire'],
  ['heart', 'rhymes', 'wound'],

  // ── New Places ──

  ['tower', 'is', 'place'],
  ['tower', 'color', 'grey'],
  ['tower', 'shape', 'pillar'],
  ['tower', 'texture', 'rough'],
  ['tower', 'evokes', 'pride'],
  ['tower', 'evokes', 'longing'],
  ['tower', 'collides', 'wind'],
  ['tower', 'collides', 'lightning'],
  ['tower', 'transforms', 'ruins'],
  ['tower', 'produces', 'shadow'],
  ['tower', 'rhymes', 'mountain'],
  ['tower', 'rhymes', 'bone'],

  ['forge', 'is', 'place'],
  ['forge', 'color', 'gold'],
  ['forge', 'sound', 'crack'],
  ['forge', 'texture', 'rough'],
  ['forge', 'evokes', 'creation'],
  ['forge', 'evokes', 'will'],
  ['forge', 'collides', 'water'],
  ['forge', 'transforms', 'iron'],
  ['forge', 'produces', 'smoke'],
  ['forge', 'produces', 'sword'],
  ['forge', 'consumes', 'stone'],
  ['forge', 'rhymes', 'furnace'],
  ['forge', 'rhymes', 'fire'],

  ['swamp', 'is', 'place'],
  ['swamp', 'color', 'green'],
  ['swamp', 'texture', 'wet'],
  ['swamp', 'sound', 'hum'],
  ['swamp', 'evokes', 'death'],
  ['swamp', 'evokes', 'forgetting'],
  ['swamp', 'collides', 'fire'],
  ['swamp', 'transforms', 'bone'],
  ['swamp', 'produces', 'fog'],
  ['swamp', 'consumes', 'light'],
  ['swamp', 'rhymes', 'grave'],
  ['swamp', 'rhymes', 'void'],

  ['abyss', 'is', 'place'],
  ['abyss', 'color', 'black'],
  ['abyss', 'shape', 'hollow'],
  ['abyss', 'evokes', 'hunger'],
  ['abyss', 'evokes', 'fear'],
  ['abyss', 'collides', 'light'],
  ['abyss', 'collides', 'star'],
  ['abyss', 'transforms', 'silence'],
  ['abyss', 'consumes', 'light'],
  ['abyss', 'consumes', 'name'],
  ['abyss', 'rhymes', 'void'],
  ['abyss', 'rhymes', 'pit'],

  ['garden', 'is', 'place'],
  ['garden', 'color', 'green'],
  ['garden', 'texture', 'soft'],
  ['garden', 'evokes', 'patience'],
  ['garden', 'evokes', 'creation'],
  ['garden', 'collides', 'fire'],
  ['garden', 'collides', 'frost'],
  ['garden', 'transforms', 'seed'],
  ['garden', 'produces', 'flower'],
  ['garden', 'produces', 'fruit'],
  ['garden', 'rhymes', 'dream'],
  ['garden', 'rhymes', 'dawn'],

  ['labyrinth', 'is', 'place'],
  ['labyrinth', 'color', 'grey'],
  ['labyrinth', 'shape', 'spiral'],
  ['labyrinth', 'evokes', 'fear'],
  ['labyrinth', 'evokes', 'memory'],
  ['labyrinth', 'collides', 'truth'],
  ['labyrinth', 'transforms', 'name'],
  ['labyrinth', 'produces', 'echo'],
  ['labyrinth', 'consumes', 'time'],
  ['labyrinth', 'rhymes', 'cave'],
  ['labyrinth', 'rhymes', 'dream'],

  ['bridge', 'is', 'place'],
  ['bridge', 'color', 'grey'],
  ['bridge', 'shape', 'arch'],
  ['bridge', 'evokes', 'fate'],
  ['bridge', 'evokes', 'trust'],
  ['bridge', 'collides', 'void'],
  ['bridge', 'transforms', 'threshold'],
  ['bridge', 'produces', 'passage'],
  ['bridge', 'rhymes', 'bone'],
  ['bridge', 'rhymes', 'rib'],

  ['altar', 'is', 'place'],
  ['altar', 'color', 'grey'],
  ['altar', 'shape', 'slab'],
  ['altar', 'texture', 'smooth'],
  ['altar', 'evokes', 'sacrifice'],
  ['altar', 'evokes', 'devotion'],
  ['altar', 'collides', 'life'],
  ['altar', 'transforms', 'blood'],
  ['altar', 'produces', 'silence'],
  ['altar', 'consumes', 'blood'],
  ['altar', 'rhymes', 'stone'],
  ['altar', 'rhymes', 'tomb'],

  ['grove', 'is', 'place'],
  ['grove', 'color', 'green'],
  ['grove', 'sound', 'whisper'],
  ['grove', 'texture', 'soft'],
  ['grove', 'evokes', 'memory'],
  ['grove', 'evokes', 'silence'],
  ['grove', 'collides', 'fire'],
  ['grove', 'transforms', 'ruins'],
  ['grove', 'produces', 'shadow'],
  ['grove', 'produces', 'root'],
  ['grove', 'rhymes', 'dream'],
  ['grove', 'rhymes', 'tomb'],

  ['chasm', 'is', 'place'],
  ['chasm', 'color', 'black'],
  ['chasm', 'shape', 'hollow'],
  ['chasm', 'sound', 'echo'],
  ['chasm', 'evokes', 'grief'],
  ['chasm', 'evokes', 'fear'],
  ['chasm', 'collides', 'bridge'],
  ['chasm', 'transforms', 'silence'],
  ['chasm', 'produces', 'echo'],
  ['chasm', 'consumes', 'light'],
  ['chasm', 'rhymes', 'pit'],
  ['chasm', 'rhymes', 'wound'],

  // ── New Flora ──

  ['fungus', 'is', 'flora'],
  ['fungus', 'color', 'white'],
  ['fungus', 'texture', 'soft'],
  ['fungus', 'evokes', 'death'],
  ['fungus', 'evokes', 'patience'],
  ['fungus', 'collides', 'light'],
  ['fungus', 'transforms', 'flesh'],
  ['fungus', 'produces', 'soil'],
  ['fungus', 'consumes', 'death'],
  ['fungus', 'rhymes', 'ghost'],
  ['fungus', 'rhymes', 'moss'],

  ['lotus', 'is', 'flora'],
  ['lotus', 'color', 'white'],
  ['lotus', 'shape', 'circle'],
  ['lotus', 'texture', 'soft'],
  ['lotus', 'evokes', 'dream'],
  ['lotus', 'evokes', 'silence'],
  ['lotus', 'collides', 'mud'],
  ['lotus', 'transforms', 'sleep'],
  ['lotus', 'produces', 'seed'],
  ['lotus', 'rhymes', 'moon'],
  ['lotus', 'rhymes', 'pearl'],

  ['reed', 'is', 'flora'],
  ['reed', 'color', 'gold'],
  ['reed', 'shape', 'pillar'],
  ['reed', 'sound', 'whisper'],
  ['reed', 'evokes', 'song'],
  ['reed', 'evokes', 'longing'],
  ['reed', 'collides', 'wind'],
  ['reed', 'transforms', 'song'],
  ['reed', 'produces', 'sound'],
  ['reed', 'rhymes', 'bone'],
  ['reed', 'rhymes', 'breath'],

  ['bramble', 'is', 'flora'],
  ['bramble', 'color', 'brown'],
  ['bramble', 'texture', 'sharp'],
  ['bramble', 'shape', 'knot'],
  ['bramble', 'evokes', 'hunger'],
  ['bramble', 'evokes', 'fear'],
  ['bramble', 'collides', 'flesh'],
  ['bramble', 'transforms', 'wound'],
  ['bramble', 'produces', 'wound'],
  ['bramble', 'produces', 'blood'],
  ['bramble', 'consumes', 'light'],
  ['bramble', 'rhymes', 'thorn'],
  ['bramble', 'rhymes', 'vine'],

  // ── New Fauna ──

  ['raven', 'is', 'fauna'],
  ['raven', 'color', 'black'],
  ['raven', 'sound', 'rasp'],
  ['raven', 'evokes', 'death'],
  ['raven', 'evokes', 'wisdom'],
  ['raven', 'collides', 'light'],
  ['raven', 'transforms', 'omen'],
  ['raven', 'produces', 'shadow'],
  ['raven', 'consumes', 'eye'],
  ['raven', 'rhymes', 'crow'],
  ['raven', 'rhymes', 'night'],

  ['stag', 'is', 'fauna'],
  ['stag', 'color', 'brown'],
  ['stag', 'shape', 'branch'],
  ['stag', 'evokes', 'pride'],
  ['stag', 'evokes', 'sacrifice'],
  ['stag', 'collides', 'wolf'],
  ['stag', 'transforms', 'bone'],
  ['stag', 'produces', 'blood'],
  ['stag', 'rhymes', 'tree'],
  ['stag', 'rhymes', 'crown'],
  ['stag', 'sound', 'crack'],

  ['leviathan', 'is', 'fauna'],
  ['leviathan', 'color', 'black'],
  ['leviathan', 'shape', 'coil'],
  ['leviathan', 'sound', 'roar'],
  ['leviathan', 'evokes', 'hunger'],
  ['leviathan', 'evokes', 'fear'],
  ['leviathan', 'collides', 'shore'],
  ['leviathan', 'transforms', 'ocean'],
  ['leviathan', 'consumes', 'silence'],
  ['leviathan', 'produces', 'flood'],
  ['leviathan', 'rhymes', 'serpent'],
  ['leviathan', 'rhymes', 'whale'],

  ['hawk', 'is', 'fauna'],
  ['hawk', 'color', 'gold'],
  ['hawk', 'shape', 'point'],
  ['hawk', 'evokes', 'wrath'],
  ['hawk', 'evokes', 'truth'],
  ['hawk', 'collides', 'serpent'],
  ['hawk', 'produces', 'wound'],
  ['hawk', 'transforms', 'wind'],
  ['hawk', 'consumes', 'flesh'],
  ['hawk', 'rhymes', 'sun'],
  ['hawk', 'rhymes', 'sword'],
  ['hawk', 'sound', 'roar'],

  ['fox', 'is', 'fauna'],
  ['fox', 'color', 'red'],
  ['fox', 'texture', 'soft'],
  ['fox', 'evokes', 'lie'],
  ['fox', 'evokes', 'hunger'],
  ['fox', 'collides', 'truth'],
  ['fox', 'transforms', 'shadow'],
  ['fox', 'produces', 'lie'],
  ['fox', 'consumes', 'silence'],
  ['fox', 'rhymes', 'flame'],
  ['fox', 'rhymes', 'shadow'],
  ['fox', 'sound', 'hush'],

  ['scarab', 'is', 'fauna'],
  ['scarab', 'color', 'gold'],
  ['scarab', 'texture', 'glossy'],
  ['scarab', 'evokes', 'sun'],
  ['scarab', 'evokes', 'death'],
  ['scarab', 'collides', 'night'],
  ['scarab', 'transforms', 'dust'],
  ['scarab', 'produces', 'light'],
  ['scarab', 'rhymes', 'beetle'],
  ['scarab', 'rhymes', 'star'],

  // ── New Items ──

  ['throne', 'is', 'item'],
  ['throne', 'color', 'gold'],
  ['throne', 'shape', 'slab'],
  ['throne', 'texture', 'smooth'],
  ['throne', 'evokes', 'pride'],
  ['throne', 'evokes', 'longing'],
  ['throne', 'collides', 'dust'],
  ['throne', 'transforms', 'ruins'],
  ['throne', 'produces', 'silence'],
  ['throne', 'rhymes', 'bone'],
  ['throne', 'rhymes', 'stone'],

  ['loom', 'is', 'item'],
  ['loom', 'color', 'brown'],
  ['loom', 'shape', 'web'],
  ['loom', 'sound', 'hum'],
  ['loom', 'evokes', 'fate'],
  ['loom', 'evokes', 'patience'],
  ['loom', 'collides', 'sword'],
  ['loom', 'transforms', 'thread'],
  ['loom', 'produces', 'thread'],
  ['loom', 'rhymes', 'spider'],
  ['loom', 'rhymes', 'tomb'],

  ['anvil', 'is', 'item'],
  ['anvil', 'color', 'black'],
  ['anvil', 'shape', 'slab'],
  ['anvil', 'texture', 'rough'],
  ['anvil', 'sound', 'crack'],
  ['anvil', 'evokes', 'creation'],
  ['anvil', 'evokes', 'endurance'],
  ['anvil', 'collides', 'fire'],
  ['anvil', 'transforms', 'iron'],
  ['anvil', 'produces', 'sound'],
  ['anvil', 'rhymes', 'stone'],
  ['anvil', 'rhymes', 'bone'],

  ['chalice', 'is', 'item'],
  ['chalice', 'color', 'gold'],
  ['chalice', 'shape', 'hollow'],
  ['chalice', 'texture', 'smooth'],
  ['chalice', 'evokes', 'sacrifice'],
  ['chalice', 'evokes', 'memory'],
  ['chalice', 'collides', 'dust'],
  ['chalice', 'transforms', 'blood'],
  ['chalice', 'produces', 'tear'],
  ['chalice', 'consumes', 'blood'],
  ['chalice', 'rhymes', 'bowl'],
  ['chalice', 'rhymes', 'moon'],

  ['chain', 'is', 'item'],
  ['chain', 'color', 'grey'],
  ['chain', 'shape', 'coil'],
  ['chain', 'sound', 'crack'],
  ['chain', 'evokes', 'fate'],
  ['chain', 'evokes', 'endurance'],
  ['chain', 'collides', 'freedom'],
  ['chain', 'transforms', 'will'],
  ['chain', 'consumes', 'freedom'],
  ['chain', 'produces', 'silence'],
  ['chain', 'rhymes', 'serpent'],
  ['chain', 'rhymes', 'bone'],

  ['lantern', 'is', 'item'],
  ['lantern', 'color', 'gold'],
  ['lantern', 'shape', 'hollow'],
  ['lantern', 'evokes', 'hope'],
  ['lantern', 'evokes', 'memory'],
  ['lantern', 'collides', 'void'],
  ['lantern', 'transforms', 'shadow'],
  ['lantern', 'produces', 'light'],
  ['lantern', 'consumes', 'shadow'],
  ['lantern', 'rhymes', 'star'],
  ['lantern', 'rhymes', 'eye'],

  ['drum', 'is', 'item'],
  ['drum', 'color', 'brown'],
  ['drum', 'shape', 'circle'],
  ['drum', 'sound', 'drum'],
  ['drum', 'texture', 'rough'],
  ['drum', 'evokes', 'heart'],
  ['drum', 'evokes', 'wrath'],
  ['drum', 'transforms', 'silence'],
  ['drum', 'collides', 'silence'],
  ['drum', 'produces', 'sound'],
  ['drum', 'produces', 'echo'],
  ['drum', 'rhymes', 'heart'],
  ['drum', 'rhymes', 'storm'],

  ['crown', 'is', 'item'],
  ['crown', 'color', 'gold'],
  ['crown', 'shape', 'circle'],
  ['crown', 'evokes', 'pride'],
  ['crown', 'evokes', 'fate'],
  ['crown', 'collides', 'dust'],
  ['crown', 'transforms', 'rust'],
  ['crown', 'produces', 'shadow'],
  ['crown', 'rhymes', 'sun'],
  ['crown', 'rhymes', 'bone'],

  ['shield', 'is', 'item'],
  ['shield', 'color', 'grey'],
  ['shield', 'shape', 'circle'],
  ['shield', 'texture', 'smooth'],
  ['shield', 'evokes', 'will'],
  ['shield', 'evokes', 'fear'],
  ['shield', 'collides', 'sword'],
  ['shield', 'transforms', 'wound'],
  ['shield', 'produces', 'shadow'],
  ['shield', 'consumes', 'wound'],
  ['shield', 'rhymes', 'stone'],
  ['shield', 'rhymes', 'bone'],

  ['key', 'is', 'item'],
  ['key', 'color', 'grey'],
  ['key', 'shape', 'point'],
  ['key', 'evokes', 'truth'],
  ['key', 'evokes', 'memory'],
  ['key', 'collides', 'silence'],
  ['key', 'transforms', 'threshold'],
  ['key', 'produces', 'echo'],
  ['key', 'consumes', 'silence'],
  ['key', 'rhymes', 'bone'],
  ['key', 'rhymes', 'tooth'],

  // ── New Celestial ──

  ['eclipse', 'is', 'celestial'],
  ['eclipse', 'color', 'black'],
  ['eclipse', 'shape', 'circle'],
  ['eclipse', 'evokes', 'fear'],
  ['eclipse', 'evokes', 'omen'],
  ['eclipse', 'collides', 'sun'],
  ['eclipse', 'collides', 'light'],
  ['eclipse', 'transforms', 'shadow'],
  ['eclipse', 'produces', 'silence'],
  ['eclipse', 'consumes', 'light'],
  ['eclipse', 'rhymes', 'death'],
  ['eclipse', 'rhymes', 'void'],

  ['comet', 'is', 'celestial'],
  ['comet', 'color', 'gold'],
  ['comet', 'shape', 'shard'],
  ['comet', 'evokes', 'fate'],
  ['comet', 'evokes', 'longing'],
  ['comet', 'collides', 'stone'],
  ['comet', 'transforms', 'ash'],
  ['comet', 'produces', 'fire'],
  ['comet', 'rhymes', 'star'],
  ['comet', 'rhymes', 'meteor'],

  ['horizon', 'is', 'celestial'],
  ['horizon', 'color', 'gold'],
  ['horizon', 'shape', 'slab'],
  ['horizon', 'evokes', 'longing'],
  ['horizon', 'evokes', 'hope'],
  ['horizon', 'collides', 'void'],
  ['horizon', 'transforms', 'dawn'],
  ['horizon', 'produces', 'light'],
  ['horizon', 'rhymes', 'threshold'],
  ['horizon', 'rhymes', 'shore'],

  ['aurora', 'is', 'celestial'],
  ['aurora', 'color', 'green'],
  ['aurora', 'color', 'violet'],
  ['aurora', 'evokes', 'dream'],
  ['aurora', 'evokes', 'memory'],
  ['aurora', 'collides', 'night'],
  ['aurora', 'transforms', 'light'],
  ['aurora', 'produces', 'silence'],
  ['aurora', 'rhymes', 'dawn'],
  ['aurora', 'rhymes', 'ghost'],

  // ── Cross-linking (new ↔ existing narrative edges) ──

  // Forces cross-links
  ['mercy', 'consumes', 'rage'],
  ['greed', 'consumes', 'patience'],
  ['betrayal', 'transforms', 'love'],
  ['envy', 'consumes', 'patience'],
  ['shame', 'consumes', 'joy'],
  ['devotion', 'collides', 'betrayal'],
  ['ruin', 'consumes', 'pride'],
  ['madness', 'consumes', 'truth'],
  ['desire', 'transforms', 'dream'],
  ['prophecy', 'collides', 'freedom'],
  ['vengeance', 'consumes', 'peace'],
  ['despair', 'consumes', 'hope'],
  ['hope', 'consumes', 'fear'],
  ['pride', 'consumes', 'mercy'],
  ['patience', 'produces', 'stone'],
  ['trust', 'produces', 'song'],
  ['creation', 'consumes', 'void'],
  ['reflection', 'collides', 'lie'],

  // Material cross-links
  ['clay', 'rhymes', 'bone'],
  ['amber', 'collides', 'ice'],
  ['obsidian', 'collides', 'gold'],
  ['silk', 'collides', 'thorn'],
  ['venom', 'transforms', 'blood'],
  ['honey', 'collides', 'venom'],
  ['copper', 'transforms', 'bell'],
  ['pearl', 'collides', 'fire'],
  ['tar', 'transforms', 'smoke'],
  ['soot', 'collides', 'light'],

  // Place cross-links
  ['tower', 'produces', 'echo'],
  ['forge', 'collides', 'ice'],
  ['swamp', 'consumes', 'bone'],
  ['abyss', 'produces', 'echo'],
  ['garden', 'consumes', 'blood'],
  ['labyrinth', 'consumes', 'name'],
  ['bridge', 'collides', 'flood'],
  ['altar', 'collides', 'blood'],
  ['grove', 'collides', 'storm'],
  ['chasm', 'collides', 'bridge'],

  // Fauna cross-links
  ['raven', 'collides', 'owl'],
  ['stag', 'rhymes', 'moon'],
  ['leviathan', 'collides', 'mountain'],
  ['hawk', 'collides', 'moth'],
  ['fox', 'rhymes', 'serpent'],
  ['scarab', 'collides', 'worm'],

  // Item cross-links
  ['throne', 'collides', 'void'],
  ['loom', 'collides', 'time'],
  ['anvil', 'collides', 'silence'],
  ['chalice', 'collides', 'void'],
  ['chain', 'collides', 'wind'],
  ['lantern', 'collides', 'night'],
  ['drum', 'collides', 'death'],
  ['crown', 'collides', 'wind'],
  ['shield', 'collides', 'fire'],
  ['key', 'collides', 'chain'],

  // Multi-category edges for new concepts
  ['thorn', 'is', 'item'],
  ['tooth', 'is', 'item'],
  ['heart', 'is', 'item'],
  ['chain', 'is', 'force'],
  ['crown', 'is', 'material'],

  // ══════════════════════════════════════════════════════════════════════
  // Edge Audit — Cross-connections
  // ══════════════════════════════════════════════════════════════════════

  // Elemental / material narrative links
  ['fire', 'transforms', 'glass'],
  ['blood', 'produces', 'salt'],
  ['grief', 'transforms', 'song'],
  ['fear', 'transforms', 'silence'],
  ['wisdom', 'consumes', 'time'],
  ['crown', 'transforms', 'throne'],
  ['forge', 'transforms', 'stone'],

  // ══════════════════════════════════════════════════════════════════════
  // Promoted Phantoms — Heavily Referenced
  // ══════════════════════════════════════════════════════════════════════

  // ── Sacrifice ──
  ['sacrifice', 'is', 'force'],
  ['sacrifice', 'color', 'red'],
  ['sacrifice', 'sound', 'hush'],
  ['sacrifice', 'evokes', 'grief'],
  ['sacrifice', 'evokes', 'fire'],
  ['sacrifice', 'collides', 'greed'],
  ['sacrifice', 'collides', 'life'],
  ['sacrifice', 'transforms', 'ash'],
  ['sacrifice', 'produces', 'silence'],
  ['sacrifice', 'consumes', 'life'],
  ['sacrifice', 'rhymes', 'altar'],
  ['sacrifice', 'rhymes', 'blood'],

  // ── Forgetting ──
  ['forgetting', 'is', 'force'],
  ['forgetting', 'color', 'grey'],
  ['forgetting', 'texture', 'smooth'],
  ['forgetting', 'evokes', 'void'],
  ['forgetting', 'evokes', 'silence'],
  ['forgetting', 'collides', 'memory'],
  ['forgetting', 'collides', 'name'],
  ['forgetting', 'transforms', 'silence'],
  ['forgetting', 'produces', 'dust'],
  ['forgetting', 'consumes', 'name'],
  ['forgetting', 'rhymes', 'mist'],
  ['forgetting', 'rhymes', 'fog'],

  // ── Endurance ──
  ['endurance', 'is', 'force'],
  ['endurance', 'color', 'grey'],
  ['endurance', 'texture', 'rough'],
  ['endurance', 'evokes', 'stone'],
  ['endurance', 'evokes', 'bone'],
  ['endurance', 'collides', 'time'],
  ['endurance', 'collides', 'hunger'],
  ['endurance', 'transforms', 'wisdom'],
  ['endurance', 'produces', 'scar'],
  ['endurance', 'consumes', 'grief'],
  ['endurance', 'rhymes', 'stone'],
  ['endurance', 'rhymes', 'iron'],

  // ── Freedom ──
  ['freedom', 'is', 'force'],
  ['freedom', 'color', 'clear'],
  ['freedom', 'sound', 'roar'],
  ['freedom', 'evokes', 'wind'],
  ['freedom', 'evokes', 'light'],
  ['freedom', 'collides', 'chain'],
  ['freedom', 'collides', 'fate'],
  ['freedom', 'transforms', 'wind'],
  ['freedom', 'produces', 'song'],
  ['freedom', 'consumes', 'fear'],
  ['freedom', 'rhymes', 'wind'],
  ['freedom', 'rhymes', 'dawn'],

]

/** All unique concept names derived from TRIPLES. */
/** Category tags used as `is` targets — not real concepts. */
export const CATEGORIES = new Set([
  'element', 'celestial', 'material', 'body', 'force',
  'place', 'flora', 'fauna', 'item',
])

export const CONCEPTS = /** @type {Set<string>} */ (
  new Set(TRIPLES.flatMap(([s, , o]) => [s, o]).filter(c => !CATEGORIES.has(c)))
)

/**
 * Build a bidirectional adjacency graph from triples.
 * Each triple [S, R, O] creates a forward edge on S and a reverse edge on O.
 * @param {Triple[]} triples
 * @returns {ConceptGraph}
 */
export function buildGraph(triples) {
  /** @type {ConceptGraph} */
  const graph = new Map()

  for (const [subject, relation, object] of triples) {
    if (!graph.has(subject)) graph.set(subject, [])
    graph.get(subject)?.push({ concept: object, relation, direction: 'fwd' })

    // Category tags (is-targets) get forward edges on the subject but never
    // become graph keys themselves — they are labels, not concepts.
    if (!CATEGORIES.has(object)) {
      if (!graph.has(object)) graph.set(object, [])
      graph.get(object)?.push({ concept: subject, relation, direction: 'rev' })
    }
  }

  return graph
}
